package-lock.json, package.json
Added [react-hook-form ](https://react-hook-form.com/) dependency for forms. 
_Performant, flexible and extensible forms with easy-to-use validation._
Includes basic validation possibilities, but other validation libraries can be also added if needed in the future, e.g. [Zod](https://zod.dev/)
https://jira.eduuni.fi/browse/OPHJOD-164
=> OPHJOD-164: add react-hook-form dependency

package-lock.json, src/components/MainLayout/SimpleNavigationList.tsx, src/routes/Tool/Competences.tsx
Add new optional props for the SimpleNavigationList.
On mobile it was required to have a a borderless and non-padding version. I thought to have to separate props instead of just e.g `mobile` for now as it might be beneficial to have them separate.
Names of the props can be changed.
https://jira.eduuni.fi/browse/OPHJOD-499
=> OPHJOD-499: Add border and padding props from SimpleNavigationList

package-lock.json, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx
optional
Removes the use of **voids** for Modal's `onClose` prop as it is now optional.
Requires the DS PR: Opetushallitus/jod-design-system/pull/81
https://jira.eduuni.fi/browse/OPHJOD-519
=> OPHJOD-519: Remove void's usage from Modal onClose prop as it is now

src/api/schema.d.ts, src/routes/Profile/Competences/loader.ts, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/loader.ts, src/routes/Profile/EducationHistory/utils.ts, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx
Adds missing update functionality to Tyopaikka. Partially fixes Koulutus (deleting one Koulutus from a Kategoria or adding a new Koulutus to an existing Kategoria is not implemented although the backend API supports that now).
Requires https://github.com/Opetushallitus/jod-yksilo/pull/44
https://jira.eduuni.fi/browse/OPHJOD-538
=> OPHJOD-538: Refactor profile API (part 1)

src/i18n/fi/translation.json, src/routes/Tool/Competences.tsx
* Remove ResultsCard from osaamiset tool. Show counts in text instead
* Some font size and color changes to relevant parts
https://jira.eduuni.fi/browse/OPHJOD-546
=> OPHJOD-546: Remove ResultsCard usage from osaamiset tool

src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Competences/GroupByAlphabet.tsx, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/Competences/constants.ts, src/routes/Tool/Competences.tsx
- Update Tools/Competences to use RoundButton for opening the filters.
- Add Profile/Competences to have RoundButton and show filters in Modal when in mobile
UI changes regarding Modal is to be done in another ticket.
https://jira.eduuni.fi/browse/OPHJOD-627
https://jira.eduuni.fi/browse/OPHJOD-635
=> OPHJOD-627 & OPHJOD-635: Use RoundButton's small version to open mobile filters

src/hooks/useLocalizedRoutes/useLocalizedRoutes.tsx, src/routes/Tool/Tool.tsx, src/routes/Tool/index.ts, src/routes/Tool/loader.ts
* In order to have stadardized way of fethcing data, a router loader is used to fetch "työmahdollisuudet" in Tool section. Now there are no manual "client.get" calls for routes.
https://jira.eduuni.fi/browse/OPHJOD-621
=> OPHJOD-621: Use route loader instead of client.get in tool

package-lock.json, src/i18n/fi/translation.json, src/routes/Tool/Tool.tsx
* Added a button for refreshing job opportunity suggestions instead of automation
* Button is disabled during fetching
* Updated to latest design system in order to use the accent variant of Button component
* Some minor translation and styling updates to the text between the new button and sliders, check the screenshot
https://jira.eduuni.fi/browse/OPHJOD-703
Translation/styling changes:
=> OPHJOD-703: Add a button in tool for updating opportunities

package-lock.json, src/routes/Tool/Tool.tsx
- Fix the issue with the Slider in narrow screens
These changes should have been in the earlier Slider use PR but I managed to get them lost somehow.
https://jira.eduuni.fi/browse/OPHJOD-800
=> OPHJOD-800: Fix issue with Slider on narrow screens

src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Competences/constants.ts, src/types.d.ts
Fix order of profile competence grouping by source to
1. TOIMENKUVA
2. KOULUTUS
3. PATEVYYS
4. KIINNOSTUS
5. MUU_OSAAMINEN
https://jira.eduuni.fi/browse/OPHJOD-706
=> OPHJOD-706: Fix order of competences by source filter

src/i18n/fi/translation.json, src/routes/Tool/Tool.tsx, src/stores/useToolStore/index.ts
* Added pagination to opportunities in tool
* Split fetching ehdotukset and työmahdollisuudet, ehdotukset don't need to be updated on page change
* Scroll to start of the results after page change
https://jira.eduuni.fi/browse/OPHJOD-829
=> OPHJOD-829: Use pagination with opportunities in tool

package-lock.json, src/i18n/fi/translation.json, src/routes/Tool/Tool.tsx
- Remove the translations no longer used with Pagination on Tool page
- Update `@jod/design-system`
Related to DS-side PR: Opetushallitus/jod-design-system/pull/159
https://jira.eduuni.fi/browse/OPHJOD-850
=> OPHJOD-850: Remove unused translations from Pagination component's usage

src/components/MainLayout/RoutesNavigationList.tsx, src/hooks/useAppRoutes/index.ts, src/routes/index.tsx
- Add indent to side nav in Profile + MegaMenu
- Uses the same component in both places
- Pages that are intend now has the path to them changed; `competences/` added to start
https://jira.eduuni.fi/browse/OPHJOD-854
=> OPHJOD-854: Update Profile's sidenav to have indents on Competences

package-lock.json, src/components/OpportunityCard/OpportunityCard.tsx, src/routes/Root/Root.tsx
- Update `@jod/design-system`
- Update to use text-tokens instead of hardcoded px values
- Choosing the nearest matching token existing
- Removed some classes that were not needed
- Moved some `text-black` classes to parent container; preventing unwanted redundancy
Main focus was to get rid of these kind of "text-token" usage `text-[12px]`, the other changes occured nearby the culprits.
https://jira.eduuni.fi/browse/OPHJOD-875
=> OPHJOD-875: Update use of tokens where applicable

src/components/HelpingToolsContent/HelpingToolLinkItem.tsx, src/components/HelpingToolsContent/HelpingToolsContent.tsx, src/components/HelpingToolsContent/index.ts, src/components/index.tsx, src/routes/Profile/utils.tsx, src/routes/Tool/Competences.tsx, src/routes/Tool/Interests.tsx
- Update the helping tools design
- hover added to the items
- increased the gap between icon and text
- Add reusable component to be used for the links
- Add `bg-todo` for the two links on Interests.
It would be possible to just use `HelpingToolLinkItem` also for the profile links (`HelpingToolProfileLinkItem`) but it looked nasty and introduced unwanted duplication.
https://jira.eduuni.fi/browse/OPHJOD-882
=> OPHJOD-882: Refactor helping tools to be reusable

src/api/schema.d.ts, src/components/OpportunityCard/OpportunityCard.tsx, src/routes/Tool/Tool.tsx, src/routes/Tool/utils.ts, src/stores/useToolStore/index.ts
Used changed backend endpoint /api/ehdotukset/tyomahdollisuudet ->  /api/ehdotukset/mahdollisuudet
Handles opportunities with type of opportunity TYOMAHDOLLISUUS or KOULUTUSMAHDOLLISUUS.
Fixed handling of opportunity 0% and removed todo highlight related in koulutusmahdollisuus % implementation.
Show related opportunity counts based on backend response.
Backend implementation PR: https://github.com/Opetushallitus/jod-yksilo/pull/85
https://jira.eduuni.fi/browse/OPHJOD-918
=> OPHJOD-918: Change ehdotus tyomahdollisuudet API to mahdollisuudet

src/i18n/fi/translation.json, src/routes/Profile/Favorites/Favorites.tsx, src/stores/useSuosikitStore/index.ts
Update Favorites page content based on selected filters.
One filter is wanted to be always selected; no case when zero filters are selected.
Now it prevents to remove the last filter on. Another option would be to toggle the filter in that case, but that might be weird to communicate for screenreader.
https://jira.eduuni.fi/browse/OPHJOD-916
=> OPHJOD-916: Update Favorites pages to change layout based on filters

src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Competences/Filters.tsx, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/Competences/constants.ts
Refactor the Competence typing logic related to filters.
No longer using `'KIINNOSTUS'` as one of the values for filters in Profile/Compentences as there is separate page for showing those (Kiinnostuksen kohteeni).
https://jira.eduuni.fi/browse/OPHJOD-944
=> OPHJOD-944: Refactor Competence type logic

src/routes/JobOpportunity/Competences.tsx, src/routes/JobOpportunity/loader.ts
Sort competences by proportion (removes sorting alphabetically; competences were already in the correct order)
https://jira.eduuni.fi/browse/OPHJOD-969
=> OPHJOD-969: Sort competences by proportion

package-lock.json, package.json, src/components/NavigationBar/NavigationBar.test.tsx, src/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
* Updated `vitest` and `@vitest/coverage-v8` packages
* Fixed a failing snapshot test. For some reason `vi.fn()` was used instead of a string in pathname.
https://jira.eduuni.fi/browse/OPHJOD-1013
=> OPHJOD-1013: Update vitest and @vitest/coverage-v8

package-lock.json, package.json, src/main.tsx
* Updated `web-vitals` dependency
* use `vitals.onINP` instead of the deprecated `vitals.onFID`
* https://github.com/GoogleChrome/web-vitals/blob/main/docs/upgrading-to-v4.md#%EF%B8%8F-deprecations
* https://web.dev/blog/inp-cwv-launch#fid_deprecation_timeline
https://jira.eduuni.fi/browse/OPHJOD-1014
=> OPHJOD-1014: Update web-vitals

src/components/OpportunityCard/OpportunityCard.tsx, src/i18n/fi/translation.json
- Improves the **OpportunityCard** component's accessibility for screenreader by little.
- Fixed typo in translation key name
- Updated to use correct translation keys for trend icon
- Fixed bug, where employment outlook dots where not showing correctly.
Visual order should be same like before but when first arriving to the card, the heading is the first one to land (previously it landed on Favorite button).
https://jira.eduuni.fi/browse/OPHJOD-1044
=> OPHJOD-1044: Improve OpportunityCard accessibility for screenreader

src/components/MegaMenu/MegaMenu.tsx, src/components/OpportunityCard/OpportunityCard.tsx, src/hooks/useEnvironment/index.ts, src/routes/JobOpportunity/JobOpportunity.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Tool/Interests.tsx, src/routes/Tool/Tool.tsx
* Create `useEnvironment` hook that check current URL to determine if user is in dev, test or prod environment
* Use the hook to hide todo sections from the UI in test and prod environment (TODO texts are still visible). Removed sections:
* Footer in MegaMenu
* Data boxes and few action buttons in `OpportunityCard`
* TODO sections and their routes in `JobOpportunity`
* Restrictions tab in `Tool`
* RIASEC and interests barometer links in helping tools section under `Interests`
https://jira.eduuni.fi/browse/OPHJOD-1062
=> OPHJOD-1062: Create useEnvironment hook and hide todo parts

.github/workflows/build.yml, .github/workflows/deploy.yml
- Update S3 sync paths and CloudFront cache invalidation
https://jira.eduuni.fi/browse/OPHJOD-1065
=> OPHJOD-1065: Update S3 sync paths and CloudFront cache invalidation

src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/i18n/fi/translation.json, src/routes/Profile/Competences/Filters.tsx, src/routes/Tool/OpportunitiesFilter.tsx, src/routes/Tool/Tool.tsx, src/routes/Tool/index.ts, src/routes/Tool/utils.ts, src/stores/useToolStore/index.ts
* Added filtering and sorting to tool opportunities
* Fixed a bug in OsaamisSuosittelija where it was possible to add duplicate skills
* Clear button not implemented at this point
* I decided to not show any numbers on the button, as it's kinda pointless since there's only 1 filter
https://jira.eduuni.fi/browse/OPHJOD-1067
=> OPHJOD-1067: Add filters and sorting to tool

src/routes/JobOpportunity/JobOpportunity.tsx, src/routes/JobOpportunity/loader.ts, src/utils/index.ts
Show occupation group as text and related esco-uri and description in english. ISCOGroups does not provide labels in fi an sv transtalation.
https://jira.eduuni.fi/browse/OPHJOD-1118
=> OPHJOD-1118: Show occupation group as localized text

src/routes/Profile/utils.tsx
Prepend missing `/yksilo` to login link generated by `generateProfileLink` function. The last card on the homepage used this and directed to an error page.
https://jira.eduuni.fi/browse/OPHJOD-1120
=> OPHJOD-1120: Prepend login url with /yksilo in generateProfileLink

src/hooks/useInitializeFilters/index.ts, src/routes/Profile/Competences/CompetenceFilters.tsx, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Competences/constants.ts, src/routes/Profile/Competences/loader.ts, src/routes/Tool/Competences.tsx
Update CompetenceFilters to use top-level; show name of työpaikka, koulutus and toiminto not the bottom-levels anymore (toimenkuva, tutkinto, pätevyys)
Using workplace as an example here
https://jira.eduuni.fi/browse/OPHJOD-1136
=> OPHJOD-1136: Update CompetenceFilters to use top-level

src/api/schema.d.ts, src/routes/Tool/Tool.tsx, src/stores/useToolStore/index.ts
Implementation of alphabetical sorting and paging of opportunities. Fixed page count when filtering is applied. 
Implementation uses the lexical order property of ehdotusDto to fetch page of sorted IDs from työ- and koulutusmahdollisuudet APIs. 
This pull request requires backend PR: 
https://jira.eduuni.fi/browse/OPHJOD-1133
=> OPHJOD-1133: Change alphabetical filtering

src/api/schema.d.ts, src/components/ExperienceTable/ExperienceTable.tsx, src/components/ExperienceTable/ExperienceTableRow.tsx, src/i18n/fi/translation.json, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/EducationHistory/modals/ImportKoskiModal.tsx
UI which provides possibility to import education from opintopolku by the opintopolku share link. 
This PR requires the backend implementation from PR: https://github.com/Opetushallitus/jod-yksilo/pull/98
E.g. link : https://testiopintopolku.fi/koski/opinnot/aktiiviset-ja-paattyneet-opinnot/9d811398176749bdbba3138772e8e6b7 can be used for the testing.
More links can be found from https://testiopintopolku.fi/koski/omattiedot when logged in as Nordea Demo test user.
UX design is POC. It provides selection of the imported data and possibility to save it to the profile.
https://jira.eduuni.fi/browse/OPHJOD-1176
=> OPHJOD-1176: Fetch koski jakolinkki data

src/i18n/fi/translation.json, src/routes/Tool/Interests.tsx
- Show selected interests from the discussion in separate "panel"
- Put selected interests for mapped interests
- so they can then be exported to profile after that
Separate [JIRA-ticket](https://jira.eduuni.fi/browse/OPHJOD-1255) was created where the UI does change to match with the design.
https://jira.eduuni.fi/browse/OPHJOD-1242
=> OPHJOD-1242: Update Interest Mapping tool to show/save selected interests

src/api/schema.d.ts, src/components/ActionButton/ActionButton.tsx, src/components/OpportunityCard/OpportunityCard.tsx, src/components/Toaster/Toaster.tsx, src/hooks/useAppRoutes/index.ts, src/hooks/useMenuClickHandler/index.ts, src/i18n/fi/translation.json, src/routes/JobOpportunity/JobOpportunity.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/Favorites/FavoritesOpportunityCardMenu.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/MyGoals/AddGoalModal.tsx, src/routes/Profile/MyGoals/MyGoals.tsx, src/routes/Profile/MyGoals/MyGoalsOpportunityCardMenu.tsx, src/routes/Profile/MyGoals/MyGoalsSection.tsx, src/routes/Profile/MyGoals/TavoiteInput.tsx, src/routes/Profile/MyGoals/index.ts, src/routes/Profile/MyGoals/loader.ts, src/routes/Profile/MyGoals/utils.ts, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/routes/Profile/index.ts, src/routes/Profile/utils.tsx, src/routes/Tool/Tool.tsx, src/routes/Tool/ToolOpportunityCardActionMenu.tsx, src/routes/index.tsx, src/stores/usePaamaratStore/index.ts, src/stores/useSuosikitStore/index.ts, src/utils/index.test.ts, src/utils/index.ts, tsconfig.node.json
* Implemented "Päämääräni" feature under profile
https://jira.eduuni.fi/browse/OPHJOD-1211
=> OPHJOD-1211: Implement "Päämääräni" feature

src/components/ExperienceTable/ExperienceTable.tsx
Fix ExperienceTable's buttons outlines getting clipped.
It required minimum of `4.5px` to fix clipping, and the next available token is `8px`. 5px would be enough but then it would be another magic number hardcoded.
https://jira.eduuni.fi/browse/OPHJOD-1229
=> OPHJOD-1229: Fix ExperienceTable's buttons outline clipping

src/routes/JobOpportunity/JobOpportunity.tsx, src/utils/index.ts
Show job opportunity task list in the list format on UI.
Backend PR changes the the työmahdollisuus imported list of tasks to line break separated string. This string is split back to a list on frontend and presented as defined in UX: design. 
https://jira.eduuni.fi/browse/OPHJOD-1216
=> OPHJOD-1216: Show job opportunity tasks in the list

src/components/LoginModal/LoginModal.tsx, src/hooks/useEscHandler/index.ts, src/hooks/useMenuClickHandler/index.ts, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/modals/AddOrEditKoulutusModal.tsx, src/routes/Profile/EducationHistory/modals/EditKoulutuskokonaisuusModal.tsx, src/routes/Profile/EducationHistory/modals/ImportKoskiModal.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/FreeTimeActivities/modals/AddOrEditPatevyysModal.tsx, src/routes/Profile/FreeTimeActivities/modals/EditVapaaAjanToimintoModal.tsx, src/routes/Profile/Interests/EditKiinnostusModal.tsx, src/routes/Profile/MyGoals/AddGoalModal.tsx, src/routes/Profile/SomethingElse/EditMuuOsaaminenModal.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx, src/routes/Profile/WorkHistory/modals/AddOrEditToimenkuvaModal.tsx, src/routes/Profile/WorkHistory/modals/EditTyonantajaModal.tsx, src/routes/Tool/VirtualAssistant.tsx
- Add ESC handler for the Modals in use.
- Pressing ESC will also close the menus (useMenuClickHandler)
The actual "permission" to close should have been checked in the given `onEscKeyDown` function. E.g like `WorkHistoryWizard` uses this same function to press "Cancel" button (currently no confirmations)
When Modal is open and focus is in input:
1. First ESC press will first remove the focus from the input.
2. Then focus automatically goes to the body
3. If then pressing ESC again, it will call the given `onEscKeyDown` function.
When Modal is open and DatePicker is opened:
1. First ESC press will first close the calendar; focus returns to the calendar button
2. Second press will remove focus from the calendar button, and focus automatically goes to the body
4. If then pressing ESC again, …
=> OPHJOD-1283: Update WorkHistoryWizard to have ESC handler

src/components/ExperienceTable/ExperienceTable.tsx
Add `padding-top` for the container for not to clip outline of the button when there is no rows in table
Tried to check if there is some other solution for these paddings, but on the other end did not use too much time as it is good for now. Before hopefully getting the overhaul for the menu moving from side to the content area's top part with narrower screen sizes.
https://jira.eduuni.fi/browse/OPHJOD-1297
https://jira.eduuni.fi/browse/OPHJOD-1277 (where these `pl-3 pt-3` could be removed )
=> OPHJOD-1297: Update ExperienceTable to not clip button in y-axis

.github/workflows/deploy.yml
Remove cache invalidation from deploy (due to account change, no access to distribution). Should not cause issues, index.html is cached only in CF and up to 60 seconds.
https://jira.eduuni.fi/browse/OPHJOD-1234
=> OPHJOD-1234: Remove cache invalidation

src/components/ExperienceTable/ExperienceTableRow.tsx, src/routes/JobOpportunity/JobOpportunity.tsx, src/utils/index.ts
When there is missing translation for get localized text with current language, fallback to get localized text with default language which is defined in src/i18n/config.ts.
Note! Uncommented the "fallbackLng: defaultLang" line in `config.ts` to enable testing of the fallback language changes.
https://jira.eduuni.fi/browse/OPHJOD-1377
=> OPHJOD-1377: Fix build issues and refactor get localization logic

src/api/schema.d.ts, src/components/ExperienceTable/ExperienceTable.tsx, src/components/ExperienceTable/ExperienceTableRow.tsx, src/components/Tooltip/TooltipWrapper.tsx, src/i18n/fi/translation.json, src/routes/BasicInformation/AboutAi.tsx, src/routes/BasicInformation/BasicInformation.tsx, src/routes/BasicInformation/index.ts, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/EducationHistory/modals/ImportKoulutusResultModal.tsx, src/routes/Profile/EducationHistory/modals/ImportKoulutusSummaryModal.tsx, src/routes/Profile/EducationHistory/utils.ts, src/routes/Root/Root.tsx, src/routes/Tool/Goals.tsx, src/routes/index.tsx
This pull request introduces improved UI feedback for the "Osaamiset" (Competence) status in the Koski education import feature. Key updates include:
- **New Attributes:** Added `osaamisetOdottaaTunnistusta` to track the competence identification status, `osaamisetTunnistusEpaonnistui` to display error when competence identification fails and `osasuoritukset`.
- **Loading Indicator:** Introduced a loading spinner for the AI-based competence recognition process.
- **Error Handling:** Implemented UI and logic for managing errors in AI-based competence detection.
- **Component Abstraction:** Refactored TooltipWrapper into a reusable standalone component.
- **New Page:** Created an 'About AI' page and linked it to the main navigation.
- **Code Cleanup:** Removed an obsolete TODO section from …
=> OPHJOD-1306: Implement UI feedback for competence status in education import

src/routes/Profile/Path/Path.tsx
* Added title to "polkuni" page
* Use index as phase titles in PathProgress (Vaihe 1, Vaihe 2 etc) like in the UI design
https://jira.eduuni.fi/browse/OPHJOD-1415
=> OPHJOD-1415: Add title to polkuni page and use index for phase titles instead of phase name

src/api/mahdollisuusService.ts, src/routes/Profile/MyGoals/MyGoals.tsx, src/routes/Profile/MyGoals/MyGoalsOpportunityCardMenu.tsx, src/routes/Profile/MyGoals/MyGoalsSection.tsx, src/routes/Profile/MyGoals/loader.ts, src/routes/Profile/MyGoals/utils.ts, src/stores/usePaamaratStore/index.ts
* Remove the usage of `reavalidator.revalidate()` to prevent reloading data from API just to update the UI, use local state more efficiently instead
* Suosikit should now update from API every time user navigates to päämääräni page
* Mahdollisuus details are now stored to paamaaraStore and used from there. This allows the details fetched in "AddGoalModal" to be used in "MyGoalsSection" without the need to refetch them.
https://jira.eduuni.fi/browse/OPHJOD-1301
=> OPHJOD-1301: Fix suosikit not updating properly when entering päämääräni page

src/components/ExperienceTable/ExperienceTableRow.tsx
This pull request restores the previous spacing logic for the `osaamiset` cell in the `ExperienceTableRow` component, as per the requirements in OPHJOD-1306. As some previous copy paste went wrong.
https://jira.eduuni.fi/browse/OPHJOD-1306
=> OPHJOD-1306: Restore spacing logic for osaamiset cell in ExperienceTableRow

src/components/MoreActionsDropdown/MoreActionsDropdown.tsx
* Fixed DS confirmation dialog not showing up when triggered from `MoreActionsDropdown` component
https://jira.eduuni.fi/browse/OPHJOD-1480
=> OPHJOD-1480: Fix MoreActionsDropdown not working with confirmation dialogs

src/components/MoreActionsDropdown/MoreActionsDropdown.tsx
* Ensure that the `MoreActionsDropdown` remains open when the user interacts with buttons in a dialog triggered by the actions menu, whether via mouse clicks or keyboard input.
https://jira.eduuni.fi/browse/OPHJOD-1492
=> OPHJOD-1492: Prevent actions dropdown from closing when clicking on a dialog

src/api/mahdollisuusService.ts, src/routes/Profile/Path/Path.tsx, src/routes/Profile/Path/modal/ProposeVaiheModal/ProposeVaiheModal.tsx, src/routes/Profile/Path/modal/ProposeVaiheModal/SelectOpportunityStep.tsx, src/stores/useEhdotetutVaiheetStore/index.ts
* When getting vaihe proposals, only education opportunities are shown
* Filters removed from vaihe proposal modal
* Added the ability to get `TypedMahdollisuus` from `mahdollisuusService` for convenience
* Also fixed 2 unrelated bugs:
* Some footer buttons were missing in vaihe proposal modal
* When modal is closed after vaihe has been saved, an error page was visible for a short period
https://jira.eduuni.fi/browse/OPHJOD-1560
=> OPHJOD-1560: Show education opportunity vaihe proposals only

src/routes/Profile/Favorites/loader.ts
Fetch all favorites when navigating to suosikkini page. It seems safe to just remove all excluded suosikki id's when navigating to suosikkini page. In päämääräni page, favorites that are already as goals are excluded, so there is no need to set any exclusions in suosikkini page.
https://jira.eduuni.fi/browse/OPHJOD-1588
=> OPHJOD-1588: Fetch all favorites in favorites page

src/i18n/fi/translation.json, src/routes/Profile/MyGoals/MyGoals.tsx, src/routes/Profile/MyGoals/MyGoalsOpportunityCardMenu.tsx
* Fixed the issue in "päämääräni" where the "lisää suosikkeja päämääräksi" would remain active even though all favorites have been selected as goals.
* Same situation would happen when deleting päämäärä, the button would stay in disabled state, even though a favorite is available
* Update info text
https://jira.eduuni.fi/browse/OPHJOD-1590
=> OPHJOD-1590: Fix the disabled status for "lisää suosikkeja päämääräksi" button

src/components/CompareTable/CompareCompetencesTable.tsx, src/components/CompareTable/CompareCompetencesTableRow.tsx, src/components/JakaumaList/JakaumaList.tsx, src/components/OpportunityDetails/OpportunityDetails.tsx, src/components/RateAiContent/RateAiContent.tsx, src/components/ScrollHeading/ScrollHeading.tsx, src/i18n/fi/translation.json, src/routes/EducationOpportunity/EducationOpportunity.tsx, src/routes/JobOpportunity/JobOpportunity.tsx, src/routes/JobOpportunity/loader.ts, src/utils/index.ts
* Updated the job opportunity page to match latest design (https://www.figma.com/design/6M2LrpSCcB0thlFDaQAI2J/cx_jod_client?node-id=12781-60181)
* Removed todo sections
* Created a dummy `RateAiContent` component, visible only in dev environments
* Use a Checkmark icon in competence list instead of a checkbox that's in the design.
* `JakaumaList` UI updated and code refactored. This component is also used in education opportunity page so UI changes are visible there as well.
* Only 10 competences are shown by default, rest are shown after "Show all" button has been pressed
https://jira.eduuni.fi/browse/OPHJOD-1653
=> OPHJOD-1653: Job opportunity design update

src/routes/Tool/Tool.tsx, src/stores/useToolStore/index.ts
Fix the bug of Tools' opportunity filter not showing anything when both "TYOMAHDOLLISUUS" and "KOULUTUSMAHDOLLISUUS" was checked as filter in Profile's Favorites and then clicking the link to go to Tools.
_Screenshot to tell what filter in the Profile's Favorites is meant and what part of the Tool was affected._
https://jira.eduuni.fi/browse/OPHJOD-1705
=> OPHJOD-1705: Fix the bug of Tool's opportunity filter

src/components/Toaster/Toaster.tsx
* Toasts now always appear 32px from the right side of the screen and 32px from the bottom of the header bar
* Added 4000ms default duration
https://jira.eduuni.fi/browse/OPHJOD-1783
=> OPHJOD-1783: Update toaster position

package-lock.json, src/components/ExperienceTable/ExperienceTableRow.tsx
- Update ExperienceTable
- tells the state, `aria-expanded`, of the menu for the competences
- the opened competences "area" has now label attached, so that user knows which are they
- Update `@jod/design/system` as it caused error because it was not updated.
https://jira.eduuni.fi/browse/OPHJOD-1881
=> OPHJOD-1881: Update ExperienceTable to be more screenreader friendly

src/components/IconHeading/index.tsx, src/components/OpportunityDetails/OpportunityDetails.tsx, src/routes/Profile/components/ProfileSectionTitle.tsx
- Update `OpportunityDetails` and `ProfileSectionTitle` to use `IconHeading`
- Add `bgClassName` and `textClassName` props for the `IconHeading`
Some examples:
https://jira.eduuni.fi/browse/OPHJOD-2077
=> OPHJOD-2077: Update to use IconHeading

src/components/RateAiContent/RateAiContent.tsx, src/i18n/fi/translation.json
- Update RateAiContent modal's content
- Fix a11y issues; was not usable with the keyboard and therefore not with a screenreader
- Use button instead of svg as an button
- Add aria labels for buttons to tell what those are
- Add explanation for the icon, as it seems informative in this case
- Add Toasts when feedback is sent
- Update to show only in **dev**
`description` prop in ConfirmDialog only supports text so therefore it did not seem possible at this time to get it correctly to change lines / separate paragraphs as in design.
--> creating ticket to backlog
https://jira.eduuni.fi/browse/OPHJOD-2222
=> OPHJOD-2222: Update RateAiContent modal, fix a11y issues, only on dev

src/i18n/fi/translation.json, src/routes/Tool/CategorizedCompetenceTagList.tsx
* Fix the removal of imported kiinnostukset in tool
* In the linked ticket it says that there should be a confirmation dialog when removing free texts that are imported from profile. When I asked about the texts from design, they said that there is no need for the dialogs and the previous ones should also be removed... For now.
https://jira.eduuni.fi/browse/OPHJOD-2011
=> OPHJOD-2011: Fix the removal of imported kiinnostukset in tool and remove confirm dialogs

src/routes/JobOpportunity/JobOpportunity.tsx
* Fixed mobile view for salary info in job opportunity, the salaries now stack vertically on mobile
* Cleaned and updated some styles, like font colors so it's a bit closer to the design.
https://jira.eduuni.fi/browse/OPHJOD-2397
=> OPHJOD-2397: Fix mobile styles for job opportunity salary information
