.github/pull_request_template.md
Add pull request template to the project.
https://jira.eduuni.fi/browse/OPHJOD-166
=> OPHJOD-166: Add pull request template

.github/workflows/storybook.yaml, .gitignore
Add GitHub workflow to deploy Storybook to GitHub Pages.
Later it helps when also other than the developers can see components which are done.
https://jira.eduuni.fi/browse/OPHJOD-173
=> OPHJOD-173: Add Storybook deployment to GH Pages

.eslintrc.cjs, package-lock.json, package.json, src/components/Button/Button.tsx, src/stories/Page.tsx
- Add eslint-plugin-sonarjs
- Add some rules to be in line with Sonarcloud
- will need to add more in the future if current rules do not catch what we want
https://jira.eduuni.fi/browse/OPHJOD-182
=> OPHJOD-182: Add eslint-plugin-sonarjs

.husky/pre-commit, .husky/pre-push, .lintstagedrc.json, package-lock.json, package.json
- Add lint-staged & husky
- linting/prettiering only staged files in pre-commit
- run unit tests pre-push 
https://jira.eduuni.fi/browse/OPHJOD-187
=> OPHJOD-187: Add husky & lint-staged

package-lock.json, package.json, src/main.tsx
Add [web-vitals](https://github.com/GoogleChrome/web-vitals) dependency
> ..library for measuring all the [Web Vitals](https://web.dev/articles/vitals) metrics on real users, in a way that accurately matches how they're measured by Chrome and reported to other Google tools
https://jira.eduuni.fi/browse/OPHJOD-170
=> OPHJOD-170: Add web-vitals dependency

LICENSE
Update license
**Related JIRA ticket**
https://jira.eduuni.fi/browse/OPHJOD-146
=> OPHJOD-146: Update license

src/features/counter/counter.tsx, src/features/counter/counterSlice.ts, src/routes/Home/index.tsx, src/routes/Root/Root.tsx, src/routes/Root/loader.test.ts, src/routes/Root/loader.ts, src/state/store.ts, tsconfig.json, vite.config.ts
Add alias to `src` directory.
Before:
`import { Button } from '../../components';`
After:
`import { Button } from '@/components';`
Same will then work other directories inside the `/src`, e.g
```
@/state
@/features
@/routes
```
**_In draft status as still some decisions to be made and thereafter possible changes regarding the PR._**
https://jira.eduuni.fi/browse/OPHJOD-194
=> OPHJOD-194: Add alias for src/ directory

package-lock.json, package.json, src/main.tsx, src/routes/Root/Root.tsx
- Add selected language to html-tag
- Add `react-helmet-async` dependency
https://jira.eduuni.fi/browse/OPHJOD-192
=> OPHJOD-193: Add language to html-tag

src/components/Button/Button.test.tsx, src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/Title/Title.test.tsx, src/components/Title/Title.tsx, src/components/index.tsx, src/routes/AboutUs/index.tsx, src/routes/Home/index.tsx, src/routes/NoMatch/index.tsx
- Update document title based on page
- Add ` - JOD` as suffix at the moment
- Uses `react-helmet-async` for updating title
https://jira.eduuni.fi/browse/OPHJOD-205
=> OPHJOD-205: Update document title based on page

vite.config.ts
- Add API proxy to development server
https://jira.eduuni.fi/browse/OPHJOD-200
=> OPHJOD-200: Add API proxy to development server

.vscode/extensions.json
- Update VS Code Vitest extension
https://jira.eduuni.fi/browse/OPHJOD-228
=> OPHJOD-228: Update VS Code vitest extension

.prettierrc
- Remove redundant default semi option
https://jira.eduuni.fi/browse/OPHJOD-183
=> OPHJOD-183: Remove redundant default semi option

.github/workflows/build.yml
- Update deploy condition in build workflow
https://jira.eduuni.fi/browse/OPHJOD-238
=> OPHJOD-238: Update deploy condition in build workflow

src/components/DropdownMenu/DropdownMenu.stories.ts, src/components/DropdownMenu/DropdownMenu.test.tsx, src/components/DropdownMenu/DropdownMenu.tsx, src/components/DropdownMenu/__snapshots__/DropdownMenu.test.tsx.snap, src/components/index.tsx
Add DropdownMenu component.
_A component from the ashes of Header skeleton that was in the works._
```tsx
type LanguageCode = 'fi' | 'sv' | 'en';
// ..
// FAIL: "ee" is not one of the allowed values here
render(<DropdownMenu<LanguageCode> label="" options={options} defaultValue="ee" />);
// SUCCESS: "en" is an allowed value
render(<DropdownMenu<LanguageCode> label="" options={options} defaultValue="en" />);
```
At minimum all the options values should have `value` and `label` properties as those are required under the hood; it will nag if those are missing. But in addition options can have more properties, e.g:
```tsx
const options = [
{ value: 'fi', population: 1, label: 'Suomi' },
{ value: 'sv', population: 2, label: 'Svenska' },
{ value: 'en', population: 3, label: 'English' },
];
``` …
=> OPHJOD-214: Add DropdownMenu component

.github/workflows/build.yml, sonar-project.properties, vite.config.ts
Enable SonarCloud code coverage report
https://jira.eduuni.fi/browse/OPHJOD-215
=> OPHJOD-215: Add code coverage report to sonarcloud

package-lock.json, package.json, src/features/counter/counter.tsx
- Rename package
- Update to use design-system's new package name
https://jira.eduuni.fi/browse/OPHJOD-260
=> OPHJOD-260: Rename package

README.md
- Add guide to update design system
https://jira.eduuni.fi/browse/OPHJOD-284
=> OPHJOD-284: Add guide to update design system

package-lock.json, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/Profile/competences.tsx, src/routes/Profile/goals.tsx, src/routes/Profile/index.tsx, src/routes/Profile/instructions.tsx, src/routes/Profile/interests.tsx, src/routes/Profile/restrictions.tsx, src/routes/Profile/search.tsx, src/routes/Root/Root.tsx
- Add Profile page with subroutes; no actual content
- Using `RoundLinkButton` as `Link` (react-router-dom)
https://jira.eduuni.fi/browse/OPHJOD-256
=> OPHJOD-256: Add Profile route with subroutes

package-lock.json, src/features/counter/counter.tsx, src/routes/Root/Root.tsx, tailwind.config.js
- Add design system preset
https://jira.eduuni.fi/browse/OPHJOD-314
=> OPHJOD-314: Add design system preset

src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/Home/index.tsx, src/routes/Root/Root.tsx
- Update home page to match with the first version of the JOD
- Removed footer
- Removed translations values that were no longer in use
- Updated `@jod/design-system` dependency
https://jira.eduuni.fi/browse/OPHJOD-310
=> OPHJOD-310: Update home page to match JOD 1st version

README.md, vite.config.ts
- Add API base URL configuration
https://jira.eduuni.fi/browse/OPHJOD-317
=> OPHJOD-317: Add API base URL configuration

package-lock.json, src/routes/BasicInformation/index.tsx, src/routes/Home/index.tsx, src/routes/Instructions/index.tsx, src/routes/Profile/index.tsx, src/routes/Root/Root.tsx
- Update main element
https://jira.eduuni.fi/browse/OPHJOD-345
=> OPHJOD-345: Update main element

package-lock.json, src/i18n/config.ts, src/routes/Root/Root.css, src/routes/Root/Root.tsx, src/routes/Root/loader.test.ts
- Add link to home page in navigation bar
https://jira.eduuni.fi/browse/OPHJOD-347
=> OPHJOD-347: Add link to home page in navigation bar

.vscode/settings.json, package-lock.json, src/components/MainLayout/MainLayout.tsx, src/components/MainLayout/SimpleNavigationList.tsx, src/components/index.tsx, src/hooks/useActionBar/index.ts, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/index.css, src/routes/BasicInformation/index.tsx, src/routes/Home/index.tsx, src/routes/Instructions/index.tsx, src/routes/Root/Root.tsx
- Add basic information routes
- Add instructions routes
https://jira.eduuni.fi/browse/OPHJOD-334
https://jira.eduuni.fi/browse/OPHJOD-344
=> Add basic information and instructions routes

src/components/Accordion/Accordion.tsx, src/components/MainLayout/MainLayout.tsx, src/components/MainLayout/RoutesNavigationList.tsx, src/components/MainLayout/SimpleNavigationList.tsx, src/components/index.tsx, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/BasicInformation/index.tsx, src/routes/Instructions/index.tsx, src/routes/PersonalPages/index.tsx, src/routes/Root/Root.tsx
- Add base of personal pages
https://jira.eduuni.fi/browse/OPHJOD-232
=> OPHJOD-232: Add base of personal pages

src/components/MainLayout/RoutesNavigationList.tsx
- Refactor routes navigation list to use unique key
https://jira.eduuni.fi/browse/OPHJOD-391
=> OPHJOD-391: Refactor routes navigation list to use unique key

package-lock.json, src/components/MainLayout/MainLayout.tsx, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/Home/index.tsx, src/routes/Root/Root.tsx, src/routes/Tool/index.tsx
Add SkipLink into use for `<main>`
https://jira.eduuni.fi/browse/OPHJOD-419
=> OPHJOD-419: Use SkipLink to for main

package-lock.json, src/App.tsx, src/components/MainLayout/MainLayout.tsx, src/hooks/useAuth/index.ts, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/Home/index.tsx, src/routes/NoInternetAccess/index.tsx, src/routes/Root/Root.tsx, src/routes/Root/loader.test.ts, src/routes/Root/loader.ts, src/routes/Tool/competences.tsx, src/routes/Tool/index.tsx, vite.config.ts
- Use and store CSRF token
https://jira.eduuni.fi/browse/OPHJOD-404
=> OPHJOD-404: Use and store CSRF token

package-lock.json, src/components/Accordion/Accordion.tsx, src/components/MainLayout/RoutesNavigationList.tsx, src/components/MainLayout/SimpleNavigationList.tsx, src/routes/NoInternetAccess/index.tsx, src/routes/PersonalPages/index.tsx, src/routes/Root/loader.ts
- Add filters to personal pages
https://jira.eduuni.fi/browse/OPHJOD-413
=> OPHJOD-413: Add filters to personal pages

package-lock.json, src/routes/PersonalPages/index.tsx
- Add draft of the Competences page to PersonalPages
- Hardcoded competences Tags as a placeholder
https://jira.eduuni.fi/browse/OPHJOD-409
=> OPHJOD-409: Add draft of PersonalPages Competences

src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/Root/Root.tsx, vite.config.ts
* Added user menu with logout button
https://jira.eduuni.fi/browse/OPHJOD-423
=> OPHJOD-423: Initial logout implementation

package-lock.json, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/Profile/WorkHistory/WorkHistoryWizard/TyopaikkaOrToimenkuvaStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx, src/routes/Profile/WorkHistory/utils.ts
- Fix work history table generation
- Use date picker component and add some validations
https://jira.eduuni.fi/browse/OPHJOD-428
https://jira.eduuni.fi/browse/OPHJOD-481
=> OPHJOD-428 & OPHJOD-481

package-lock.json, src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/components/index.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/CompetencesStep.tsx
* Refactored the `ConnectedCompetences` component into reusable `OsaamisSuosittelija` component.
https://jira.eduuni.fi/browse/OPHJOD-488
=> OPHJOD-488: Refactor OsaamisSuosittelija into own reusable component

.github/workflows/build.yml, .gitignore, README.md, src/routes/Home/Home.tsx
- Sync third party assets from S3 bucket
https://jira.eduuni.fi/browse/OPHJOD-315
=> OPHJOD-315: Sync third party assets from S3 bucket

package-lock.json, src/index.css, tailwind.config.ts
- Include assets from design system
https://jira.eduuni.fi/browse/OPHJOD-495
=> OPHJOD-495: Include assets from design system

.github/workflows/build.yml
- Fix dist downloading
https://jira.eduuni.fi/browse/OPHJOD-315
=> OPHJOD-315: Fix dist downloading

src/routes/Tool/Competences.tsx
- Drafting of the page; keeping mobile in mind
- No actual actions
- See comments in JIRA to related tickets of possible future changes to Modal and Accordion components
https://jira.eduuni.fi/browse/OPHJOD-485
=> OPHJOD-485: Tools/Competences page drafting and mobile support

.eslintrc.cjs, package-lock.json, package.json, src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/hooks/useActionBar/index.ts, src/hooks/useAuth/index.ts, src/hooks/useDebounceState/index.ts, src/routes/Profile/Competences.tsx, src/routes/Profile/EducationHistory.tsx, src/routes/Profile/Favorites.tsx, src/routes/Profile/FreeTimeActivities.tsx, src/routes/Profile/Preferences.tsx, src/routes/Profile/SomethingElse.tsx, src/routes/Profile/WorkHistory/WorkHistory.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/SummaryStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx, src/routes/Root/Root.tsx
* React imports refactor and ESLint rule (Yksilö UI portion)
https://jira.eduuni.fi/browse/OPHJOD-447
=> OPHJOD-447: React imports refactor and ESLint rule

src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/routes/Tool/Competences.tsx
Add OsaamisSuosittelija component to use on the Tools/Competences page.
Able to show competences based on search and select those; not saving selected ones anywhere at the moment.
https://jira.eduuni.fi/browse/OPHJOD-484
=> OPHJOD-484: Add OsaamisSuosittelija to Tools/Competences page

src/routes/Profile/WorkHistory/utils.ts
- Refactor getWorkHistoryTableRows to handle end dates
https://jira.eduuni.fi/browse/OPHJOD-479
=> OPHJOD-479: Refactor getWorkHistoryTableRows to handle end dates

src/api/schema.d.ts, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivities.tsx, src/routes/Profile/FreeTimeActivities/loader.ts
Update API usage after backend changes
https://jira.eduuni.fi/browse/OPHJOD-490
=> OPHJOD-490: Update API usage after backend changes

src/i18n/en/translation.json, src/i18n/fi/translation.json, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/ActivityStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/ProfiencyStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/SummaryStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/utils.ts
Add ability to add new free time activities.
At the same time the editing functionality was added.
https://jira.eduuni.fi/browse/OPHJOD-491
https://jira.eduuni.fi/browse/OPHJOD-491
=> OPHJOD-491: Add ability to add new/edit free time activities

src/App.tsx, src/i18n/sv/translation.json
- Fix multiple rendering of app
https://jira.eduuni.fi/browse/OPHJOD-522
=> OPHJOD-522: Fix multiple rendering of app

src/components/OpportunityCard/OpportunityCard.tsx, src/routes/Tool/Competences.tsx
Add a draft/skeleton of the OpportunityCard component for showing opportunities for work or education/courses.
Using some hardcoded fake data for now.
https://jira.eduuni.fi/browse/OPHJOD-235
=> OPHJOD-235: Add draft of the OpportunityCard for Tool/Competences

package-lock.json, src/App.tsx, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/Tool/MatchedLink.tsx, src/routes/Tool/Search.tsx, src/routes/Tool/Tool.tsx, src/routes/Tool/index.ts
Update Tools selection buttons layout behaviour on desktop/mobile
Remove the Search page as it is not needed and did not have actual content/actions at all.
https://jira.eduuni.fi/browse/OPHJOD-525
=> OPHJOD-525: Update Tools layout work better for mobile

src/App.tsx, src/components/MainLayout/RoutesNavigationList.tsx, src/components/OpportunityCard/OpportunityCard.tsx, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/JobOpportunity/Competences.tsx, src/routes/JobOpportunity/JobOpportunity.tsx, src/routes/JobOpportunity/Overview.tsx, src/routes/JobOpportunity/Tabs.tsx, src/routes/JobOpportunity/index.ts, src/routes/JobOpportunity/utils.ts, src/routes/Tool/Competences.tsx
- Add job opportunity base
https://jira.eduuni.fi/browse/OPHJOD-236
=> OPHJOD-236: Add job opportunity base

src/api/schema.d.ts, src/components/OpportunityCard/OpportunityCard.tsx, src/routes/Tool/Competences.tsx
Update Tool/Competences to get data from backend instead of the mocked data
Also a small fix to OpportunityCard as it was not round as it should have been when on desktop.
https://jira.eduuni.fi/browse/OPHJOD-528
=> OPHJOD-528: Update Tool/Competences to get data from backend

src/App.tsx, src/routes/AuthGuard.tsx
Created a basic auth guard component that prevents the user navigation to secured routes without authentication.
https://jira.eduuni.fi/browse/OPHJOD-445
=> OPHJOD-445: Auth guard component

package-lock.json, src/components/MainLayout/RoutesNavigationList.tsx, src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/components/SelectableTable/SelectableTable.tsx, src/routes/JobOpportunity/Competences.tsx, src/routes/JobOpportunity/Overview.tsx, src/routes/JobOpportunity/Tabs.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/CompetencesStep.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationStep.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/SummaryStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/ActivityStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/ProfiencyStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/SummaryStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/CompetencesStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/SummaryStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkplaceStep.tsx, src/routes/Root/Root.tsx, src/routes/Tool/Competences.tsx
Use latest DS and replace "primary-gray" with "black" in classnames
https://jira.eduuni.fi/browse/OPHJOD-569
=> OPHJOD-569: Update DS and replace primary-gray with black in classnames

package-lock.json, src/routes/Root/Root.tsx
Add background color to body as in the updated design. Using `bg-gray` token.
https://jira.eduuni.fi/browse/OPHJOD-571
=> OPHJOD-571: Add background color for body

src/hooks/useActionBar/index.ts, src/routes/Root/Root.tsx
- Update footer and action bar bg color
https://jira.eduuni.fi/browse/OPHJOD-573
=> OPHJOD-573: Update footer and action bar bg color

src/api/schema.d.ts, src/hooks/useAuth/index.ts, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Root/Root.tsx, src/routes/Root/loader.test.ts, src/routes/Root/loader.ts
- Fix CSRF typings
https://jira.eduuni.fi/browse/OPHJOD-536
=> OPHJOD-536: Fix CSRF typings

src/api/schema.d.ts, src/routes/Tool/Competences.tsx
Update Tyomahdollisuus API and fix typings
https://jira.eduuni.fi/browse/OPHJOD-459
=> OPHJOD-459: Update Tyomahdollisuus API and fix typings

package-lock.json, src/routes/Tool/Competences.tsx
Update the Slider usage after the icon removal and increase gap
https://jira.eduuni.fi/browse/OPHJOD-542
=> OPHJOD-542: Update the Slider usage after icon removal and DS change

.vscode/settings.json, src/api/schema.d.ts, src/i18n/fi/translation.json, src/routes/Profile/Preferences/Preferences.tsx
- Add user deleting
https://jira.eduuni.fi/browse/OPHJOD-535
=> OPHJOD-535: Add user deleting

package-lock.json, src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx
Update OsaamisSuosittelija to match with the updated design.
No separate label anymore, but the same text is now as `aria-label` so the screenreader user knows where focus is when adding/removing the competences.
https://jira.eduuni.fi/browse/OPHJOD-544
=> OPHJOD-544: Update OsaamisSuosittelija to match design

package-lock.json, src/components/MainLayout/RoutesNavigationList.tsx, src/components/MainLayout/SimpleNavigationList.tsx, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/Favorites.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivities.tsx, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Profile/SomethingElse.tsx, src/routes/Profile/WorkHistory/WorkHistory.tsx
* Side menu (`RoutesNavigationList` component) design update
https://jira.eduuni.fi/browse/OPHJOD-548
=> OPHJOD-548: Update NavigationList component to match current design

.github/workflows/build.yml, .github/workflows/deploy.yml, .gitignore, README.md, index.html, src/routes/Home/Home.tsx
Add deploy workflow that supports deploying to multiple environments.
https://jira.eduuni.fi/browse/OPHJOD-583
=> OPHJOD-583: Add deploy workflow

.github/workflows/build.yml
Deploy to test on push to main (requiresapproval)
https://jira.eduuni.fi/browse/OPHJOD-583
=> OPHJOD-583: Add deploy job for test env

.github/workflows/deploy.yml
Fix concurrency group in workflow level does not see inputs context
https://jira.eduuni.fi/browse/OPHJOD-583
=> OPHJOD-583: Fix concurrency group

src/api/schema.d.ts, src/main.tsx, src/routes/Profile/Competences/loader.ts, src/routes/Profile/EducationHistory/EducationHistoryWizard/SummaryStep.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/utils.ts, src/routes/Profile/EducationHistory/modals/EditKoulutusModal.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/SummaryStep.tsx
Update profile management to match API. Small fixes.
(see also https://github.com/Opetushallitus/jod-yksilo/pull/47)
https://jira.eduuni.fi/browse/OPHJOD-581
=> OPHJOD-581

package-lock.json, src/components/MainLayout/SimpleNavigationList.tsx, src/routes/Root/Root.tsx
Updated design system dependency and made required changes that the PopupList refactor required.
https://jira.eduuni.fi/browse/OPHJOD-584
=> OPHJOD-584: PopupList refactor changes

.github/workflows/deploy.yml, src/api/schema.d.ts, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Root/Root.tsx, vite.config.ts
Changes login and logout to work with SAML2 authentication.
https://jira.eduuni.fi/browse/OPHJOD-212
=> OPHJOD-212: Suomi.fi authentication PoC

src/components/MainLayout/SimpleNavigationList.tsx, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Competences/GroupByAlphabet.tsx, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/Competences/constants.ts
* Osaamiset page design update:
* Fonts
* Skill colorization
* Accordions removed from results
* Group/sort by box background colors changed and removed labels/sublabels
> [!IMPORTANT]
Checkbox and radio buttons will be updated in design system on a separate ticket
https://jira.eduuni.fi/browse/OPHJOD-557
=> OPHJOD-557: Osaamiset page design update

package-lock.json, src/routes/Home/Home.tsx
* Update DS
* Implement the required changes for updated HeroCard component
https://jira.eduuni.fi/browse/OPHJOD-549
=> OPHJOD-549: Update DS and implement HeroCard changes

package-lock.json, package.json, src/api/schema.d.ts, src/i18n/fi/translation.json, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Root/Root.tsx
Remove usage of avatar image of the user profile.
https://jira.eduuni.fi/browse/OPHJOD-589
=> OPHJOD-589: Remove usage of user profile avatar image

package-lock.json, src/components/MainLayout/SimpleNavigationList.tsx, src/routes/Tool/Competences.tsx
* Tool/osaamiset design update:
* Filters are no longer accordions
* Background color changed
* Labels removed
* Placeholder texts changed
* Design system also updated   
https://jira.eduuni.fi/browse/OPHJOD-545
=> OPHJOD-545: Osaamiset tool filters design update

package-lock.json, src/i18n/config.ts, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/index.css, src/routes/Root/Root.tsx
Implementation of language selector to main menu. Added support of following languages: 
- Finnish (full translations)
- Swedish (only some frontpage text for the verification)
- English (only some frontpage text for the verification)
https://jira.eduuni.fi/browse/OPHJOD-424
=> OPHJOD-424: Add language selector

src/routes/Profile/Competences/Competences.tsx, src/routes/Tool/Competences.tsx
* Update DS and remove unneeded empty label props from RadioButtonGroups
https://jira.eduuni.fi/browse/OPHJOD-594
=> OPHJOD-594: Update DS and remove empty RadioButtonGroup label props

src/App.tsx, src/hooks/useLanguage/index.ts, src/routes/Root/Root.tsx
- Store lang menu selection to session storage to keep it remain over the login by the useLanguage hook.
- Read language from store when initializing the router.
https://jira.eduuni.fi/browse/OPHJOD-610
=> OPHJOD-610: store lang selection to session storage

package-lock.json, src/components/MainLayout/RoutesNavigationList.tsx, src/components/MegaMenu/MegaMenu.tsx, src/routes/Root/Root.tsx
Added MegaMenu component
https://jira.eduuni.fi/browse/OPHJOD-443
Desktop
Mobile
=> OPHJOD-443: Add MegaMenu

package-lock.json, package.json
Update Vite to latest version
https://jira.eduuni.fi/browse/OPHJOD-615
=> OPHJOD-615: Update Vite

README.md, package-lock.json, src/components/OpportunityCard/OpportunityCard.tsx, src/routes/Home/Home.tsx
- Fix responsiveness
https://jira.eduuni.fi/browse/OPHJOD-400
=> OPHJOD-400: Fix responsiveness

src/i18n/fi/translation.json, src/routeDefinitions/profileRoutes.ts, src/routeDefinitions/toolRoutes.ts, src/routeDefinitions/userGuideRoutes.ts, src/routes/Profile/Profile.tsx, src/routes/Root/Root.tsx, src/routes/UserGuide/UserGuide.tsx
* Populate MegaMenu with working links
https://jira.eduuni.fi/browse/OPHJOD-617
=> OPHJOD-617: Populate MegaMenu with navigation links

src/i18n/en/translation.json, src/i18n/sv/translation.json, src/routes/Root/Root.tsx
Add translations of localized url and navigate to main page when language is changed.
This implementation does not switch URL Path  language. 
https://jira.eduuni.fi/browse/OPHJOD-612
=> OPHJOD-612: Add route translations

package-lock.json, src/index.css, tailwind.config.ts
- Update prefix to Tailwind
https://jira.eduuni.fi/browse/OPHJOD-501
=> OPHJOD-501: Update prefix to Tailwind

src/i18n/fi/translation.json
Fix the translation value for the Goals' page for one SelectionCard; this mistake was found in the review session.
https://jira.eduuni.fi/browse/OPHJOD-233
=> OPHJOD-233: Fix translation value for Goals page

src/index.css
- Fix Tailwind import order
https://jira.eduuni.fi/browse/OPHJOD-637
=> OPHJOD-637: Fix Tailwind import order

src/components/MegaMenu/MegaMenu.tsx, src/routes/Root/Root.tsx
Improve the MegaMenu scoll on low height screen on desktop or mobile, where the content was not able to be scrolled.
https://jira.eduuni.fi/browse/OPHJOD-639
=> OPHJOD-639: Fix MegaMenu scroll

package-lock.json, package.json, src/components/NavigationBar/NavigationBar.test.tsx, src/components/NavigationBar/NavigationBar.tsx, src/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/components/index.tsx, src/routes/Root/Root.tsx, tsconfig.node.json, vite.config.ts, vitest.setup.ts
* Transferred NavigationBar from DS
https://jira.eduuni.fi/browse/OPHJOD-631
=> OPHJOD-631: Transfer NavigationBar from DS

src/routes/Profile/Competences/Competences.tsx, src/routes/Tool/Competences.tsx
Update to use `hideLabel` prop of the RadioButtonGroup.
https://jira.eduuni.fi/browse/OPHJOD-633
=> OPHJOD-633: Update to use hideLabel for RadioButtonGroup

src/components/LanguageButton/LanguageButton.tsx, src/components/LanguageMenu/LanguageMenu.tsx, src/components/MegaMenu/MegaMenu.tsx, src/components/NavigationBar/NavigationBar.test.tsx, src/components/NavigationBar/NavigationBar.tsx, src/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/components/UserButton/UserButton.tsx, src/components/index.tsx, src/routes/Root/Root.tsx
* Mobile navigation changed drastically
* Some code refactor for reusability
* Language selector highlights the current language in desktop mode too
https://jira.eduuni.fi/browse/OPHJOD-630
=> OPHJOD-630: Refactor mobile navigation

src/components/OpportunityCard/OpportunityCard.tsx, src/i18n/fi/translation.json, src/routes/Tool/Competences.tsx
* Update OpportunityCard
https://jira.eduuni.fi/browse/OPHJOD-629
**Desktop**
**Mobile**
=> OPHJOD-629: Update OpportunityCard component

src/components/MainLayout/MainLayout.tsx, src/routes/Tool/Competences.tsx
* Changed grid layout to use 3 columns instead of 6
* Clicked through the whole UI and compared it to current dev environment -> Nothing broken
https://jira.eduuni.fi/browse/OPHJOD-662
=> OPHJOD-662: Change grid layout from 6 columns to 3 columns

src/routes/Tool/Competences.tsx, src/routes/Tool/Tool.tsx
Update Tools structure to have common results section at lthe lower part of the screen; sliders, opportunities, filters, etc.
https://jira.eduuni.fi/browse/OPHJOD-636
=> OPHJOD-636: Update Tools structure

src/components/OpportunityCard/OpportunityCard.tsx, src/routes/Tool/Goals.tsx, src/routes/Tool/Tool.tsx
- Fix setting of the `font-size` in OpportunityCard for the `name` prop
- Update text to wrap with longer content
- Update Goals page to wrap for SelectionCards so they all can be visible on narrow screen before changing to mobile
- Update Tools page to use the three column layout instead of the old 6
https://jira.eduuni.fi/browse/OPHJOD-666
=> OPHJOD-666: Update OpportunityCard, Goals- & Tool pages

src/components/OpportunityCard/OpportunityCard.tsx
Update to use icons from the `react-icons` library for OpportunityCard
https://jira.eduuni.fi/browse/OPHJOD-665
=> OPHJOD-665: Use icons from library

src/routes/Profile/Competences/Competences.tsx
Fix the filter button icon to be taken from the `react-icons` library.
https://jira.eduuni.fi/browse/OPHJOD-627
=> OPHJOD-627: Fix filter button icon on Profile/Competences

src/providers/ErrorNoteProvider/index.tsx
* Memoize ErrorNoteProvider value to prevent extra renders
https://jira.eduuni.fi/browse/OPHJOD-678
=> OPHJOD-678: Memoize ErrorNoteProvider value to prevent extra renders

package-lock.json, src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/constants.ts, src/i18n/fi/translation.json, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Competences/GroupByAlphabet.tsx, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/CompetencesStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/CompetencesStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/CompetencesStep.tsx, src/routes/Tool/Interests.tsx, src/routes/Tool/loader.ts, src/types.d.ts
- Fix Tag component to use correct colors
https://jira.eduuni.fi/browse/OPHJOD-626
=> OPHJOD-626: Fix Tag component to use correct colors

src/api/schema.d.ts, src/components/OpportunityCard/OpportunityCard.tsx, src/routes/Tool/Tool.tsx, src/routes/Tool/loader.ts
This Change uses new /api/ehdotus/tyomahdollisuudet and /api/tyomahdollisuudet APIs for fetching the of the Työmahdollisuus ehdotukset and populating the työmahdollisuudet cards by the %-score of tyomahdollisuusehdotus.
This PR requires use of backend PR: https://github.com/Opetushallitus/jod-yksilo/pull/60
https://jira.eduuni.fi/browse/OPHJOD-646
=> OPHJOD-646: Use new tyomahdollisuus ehdotukset API

vite.config.ts
- Update API base URL to use port 9080 instead of 8080
https://jira.eduuni.fi/browse/OPHJOD-712
=> OPHJOD-712: Update API base URL to use port 9080 instead of 8080

.vscode/launch.json, README.md, playwright.config.ts
- Update rest port changes
https://jira.eduuni.fi/browse/OPHJOD-712
=> OPHJOD-712: Update rest port changes

src/components/ExperienceTable/ExperienceTable.tsx, src/i18n/fi/translation.json, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationStep.tsx, src/routes/Profile/EducationHistory/modals/EditKoulutusModal.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/ActivityStep.tsx, src/routes/Profile/FreeTimeActivities/modals/EditPatevyysModal.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkplaceStep.tsx, src/routes/Profile/WorkHistory/modals/EditToimenkuvaModal.tsx
- Fix some translations
https://jira.eduuni.fi/browse/OPHJOD-711
=> OPHJOD-711: Fix some translations

src/routes/Tool/Tool.tsx
Fix a typo in request payload
https://jira.eduuni.fi/browse/OPHJOD-646
=> OPHJOD-646: Fix typo in request payload

src/hooks/useLocalizedRoutes/useLocalizedRoutes.tsx
Fix the issue where use presses reload while on the `/profile/*` page. It redirected to the suomi.fi identification even when session was not expired.
https://jira.eduuni.fi/browse/OPHJOD-671
=> OPHJOD-671: Fix restrictedLoader on browser reload

src/components/OpportunityCard/OpportunityCard.tsx
- Fix match percentage display
https://jira.eduuni.fi/browse/OPHJOD-679
=> OPHJOD-679: Fix match percentage display

src/components/ExperienceTable/ExperienceTableRow.tsx
* Update ExperienceTableRow to have bigger click area
* whole cell is now clickable, not just the "text"
There was discussion today that this table needs some PAMU thinking and maybe whole row to be clicked etc. But this is just a little improvement to current state while waiting those changes.
https://jira.eduuni.fi/browse/OPHJOD-729
=> OPHJOD-729: Update ExperienceTableRow to have bigger click area

src/api/schema.d.ts, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Root/loader.ts
Move yksilo endpoint under profiili
https://jira.eduuni.fi/browse/OPHJOD-782
=> OPHJOD-782: Move yksilo endpoint under profiili

package-lock.json, src/routes/Home/Home.tsx
- Refactor Home to Link instead of onClick handler
https://jira.eduuni.fi/browse/OPHJOD-791
=> OPHJOD-791: Refactor Home to Link instead of onClick handler

src/api/osaamiset.test.ts, src/api/osaamiset.ts, src/api/schema.d.ts, src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/routes/JobOpportunity/loader.ts
OPHJOD-730: Update OsaamisSuosittelija to use new API
https://jira.eduuni.fi/browse/OPHJOD-730
=> OPHJOD-730: Update OsaamisSuosittelija to use new API

src/components/MainLayout/RoutesNavigationList.tsx, src/components/MegaMenu/MegaMenu.tsx
- Fix profile links in mega menu
https://jira.eduuni.fi/browse/OPHJOD-799
=> OPHJOD-799: Fix profile links in mega menu

package-lock.json, src/routes/Home/Home.tsx
- Refactor home route to adjust hero layout
https://jira.eduuni.fi/browse/OPHJOD-803
=> OPHJOD-803: Refactor home route to adjust hero layout

src/i18n/fi/translation.json, src/routes/Tool/Competences.tsx, src/routes/Tool/Interests.tsx
Add icons for helper tools
https://jira.eduuni.fi/browse/OPHJOD-726
=> OPHJOD-726: Add icons for helper tools

src/routes/Home/Home.tsx
- Refactor home route to display appropriate hero card links
https://jira.eduuni.fi/browse/OPHJOD-802
=> OPHJOD-802: Refactor home route to display appropriate hero card links

src/api/schema.d.ts, src/hooks/useAppRoutes/index.ts, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Interests/EditKiinnostusModal.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/Interests/index.ts, src/routes/Profile/Interests/loader.ts, src/routes/index.tsx
* Created "Kiinnostuksen kohteeni" page to profile
* Created a modal for adding and removing skills of interest
https://jira.eduuni.fi/browse/OPHJOD-642
=> OPHJOD-642: Create kiinnostuksen kohteeni page

src/routes/Profile/EducationHistory/utils.ts, src/routes/Profile/FreeTimeActivities/utils.ts, src/routes/Profile/WorkHistory/utils.ts
- Refactor code to calculate count of unique skills
https://jira.eduuni.fi/browse/OPHJOD-724
=> OPHJOD-724: Refactor code to calculate count of unique skills

src/routes/Tool/Competences.tsx, src/routes/Tool/Interests.tsx, src/routes/Tool/Tool.tsx, src/routes/Tool/loader.ts
* Populate OsaamisSuosittelija with interests from profile
https://jira.eduuni.fi/browse/OPHJOD-681
=> OPHJOD-681: Populate interests in tool

package-lock.json, src/routes/Tool/Tool.tsx
Fixes Tool page problem with narrow screen where one button wraps to another row.
**In draft mode** as it requires the PR from DS-side: Opetushallitus/jod-design-system/pull/147
https://jira.eduuni.fi/browse/OPHJOD-816
=> OPHJOD-816: Fix Tool-page toolbar display problem with narrow screen

src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Competences/GroupByAlphabet.tsx, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/Competences/constants.ts
* Removed deleting functionality from osaamiseni profile page. Tags are now static.
https://jira.eduuni.fi/browse/OPHJOD-818
=> OPHJOD-818: Remove delete functionality from osaamiseni profile page

src/api/client.ts, src/api/middlewares/resetTool.ts, src/i18n/fi/translation.json, src/routes/Root/ErrorBoundary.tsx, src/stores/useToolStore/index.ts
- Refactor home route to clear tool store
https://jira.eduuni.fi/browse/OPHJOD-813
=> OPHJOD-813: Clear tool store after editing profile

src/routes/Tool/Competences.tsx
Colors was not working on some browsers.
https://jira.eduuni.fi/browse/OPHJOD-726
Before:
After:
=> OPHJOD-726: fix colors not working in all browsers

package-lock.json, src/routes/Home/Home.tsx, src/routes/Root/Root.tsx
- Refactor home route in mobile
https://jira.eduuni.fi/browse/OPHJOD-806
=> OPHJOD-806: Refactor home route in mobile

src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/utils/index.test.ts, src/utils/index.ts
Sort competence tags alphabetically following views: 
omat-sivuni/osaamiseni
/omat-sivuni/kiinnostukseni
/omat-sivuni/muut-osaamiset
https://jira.eduuni.fi/browse/OPHJOD-817
=> OPHJOD-817: Sort skills alphabetically

src/routes/Tool/Competences.tsx, src/routes/Tool/Interests.tsx
- Mark parts that are not implemented
https://jira.eduuni.fi/browse/OPHJOD-700
=> OPHJOD-700: Mark parts that are not implemented

src/hooks/useAppRoutes/index.ts, src/i18n/fi/translation.json, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/Favorites.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivities.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/routes/Profile/WorkHistory/WorkHistory.tsx, src/routes/Tool/Competences.tsx, src/routes/Tool/Goals.tsx, src/routes/Tool/Interests.tsx
* Updated profile with available translations on Figma
* Added translated filter options to favorites with placeholder functionality
* Some font and size changes in tool
https://jira.eduuni.fi/browse/OPHJOD-833
=> OPHJOD-833: Replace most placeholder texts in profile with translations

src/components/MainLayout/MainLayout.tsx, src/index.css
- Add scrollbar to MainLayout
https://jira.eduuni.fi/browse/OPHJOD-823
=> OPHJOD-823: Add scrollbar to MainLayout

src/routes/Home/Home.tsx, src/routes/Profile/utils.ts, src/routes/Profile/utils.tsx, src/routes/Tool/Competences.tsx, src/routes/Tool/Interests.tsx
- Add links to Competences and Interests tool pages
- Moved the link logic used in Home under `/Profile/utils` to be more logical place after the reuse
https://jira.eduuni.fi/browse/OPHJOD-836
=> OPHJOD-836: Update Tool helping tools to be links

package-lock.json, src/i18n/fi/translation.json, src/routes/Tool/Tool.tsx
* Show spinner inside update opportunities button while loading in tool
* Update DS
https://jira.eduuni.fi/browse/OPHJOD-805
=> OPHJOD-805: Show spinner when updating opportunities

src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/routes/JobOpportunity/Competences.tsx, src/routes/JobOpportunity/Overview.tsx, src/routes/Profile/Competences/GroupByAlphabet.tsx, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/utils.ts, src/routes/Profile/EducationHistory/modals/EditKoulutusModal.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/utils.ts, src/routes/Profile/FreeTimeActivities/modals/EditPatevyysModal.tsx, src/routes/Profile/Interests/EditKiinnostusModal.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/SomethingElse/EditMuuOsaaminenModal.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/utils.ts, src/routes/Profile/WorkHistory/modals/EditToimenkuvaModal.tsx, src/routes/Tool/Tool.tsx, src/routes/Tool/loader.ts, src/utils/index.ts
- Fix names of competences if langauge changes
https://jira.eduuni.fi/browse/OPHJOD-825
=> OPHJOD-825: Fix names of competences if langauge changes

.github/workflows/deploy.yml
Update index.html caching to avoid stale versions.
https://jira.eduuni.fi/browse/OPHJOD-809
=> OPHJOD-809: Update cache control

src/routes/JobOpportunity/Competences.tsx, src/routes/JobOpportunity/Overview.tsx, src/routes/Tool/Tool.tsx
- Add sticky to tool filters and fix scrolling in job opportunity
https://jira.eduuni.fi/browse/OPHJOD-841
=> OPHJOD-841: Add sticky to tool filters and fix scrolling in job opportunity

index.html
- Add noscript for JavaScript disabled message
https://jira.eduuni.fi/browse/OPHJOD-847
=> OPHJOD-847: Add noscript for JavaScript disabled message

src/i18n/fi/translation.json, src/routes/Profile/SomethingElse/SomethingElse.tsx
Update layout of something else view to latest UI design.
https://jira.eduuni.fi/browse/OPHJOD-857
=> OPHJOD-857: Update something else by the UI design

package-lock.json, src/api/middlewares/resetTool.ts, src/api/schema.d.ts, src/components/OpportunityCard/OpportunityCard.tsx, src/i18n/fi/translation.json, src/routes/Tool/Tool.tsx, src/routes/Tool/loader.ts, src/routes/Tool/types.d.ts, src/stores/useToolStore/index.ts, src/utils/index.ts
* Add the ability to toggle job opportunities favorite status with a star icon
* ~~Toggling with the checkboxes like in design (except removing from favorites, as I think the poc approach will  be favored instead of checkboxes)~~
* Show a login dialog for non-authenticated users who try to toggle favorite.
https://jira.eduuni.fi/browse/OPHJOD-828
=> OPHJOD-828: Implement favorite functionality to tool

src/components/MegaMenu/MegaMenu.tsx, src/components/NavigationBar/NavigationBar.tsx, src/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
- Increase navigation bar height
https://jira.eduuni.fi/browse/OPHJOD-808
=> OPHJOD-808: Increase navigation bar height

src/api/schema.d.ts, src/routes/Tool/loader.ts, src/stores/useToolStore/index.ts
Update API schema
See also https://github.com/Opetushallitus/jod-yksilo/pull/80
https://jira.eduuni.fi/browse/OPHJOD-872
=> OPHJOD-872: Update API schema

src/i18n/fi/translation.json, src/routes/EducationOpportunity/Competences.tsx, src/routes/EducationOpportunity/EducationOpportunity.tsx, src/routes/EducationOpportunity/Overview.tsx, src/routes/EducationOpportunity/Tabs.tsx, src/routes/EducationOpportunity/index.ts, src/routes/EducationOpportunity/loader.ts, src/routes/index.tsx
* Created routes and a placeholder page for education opportunity
* Page layout/structure is from job opportunity page with majority of the sections removed
* Have the loader return a mocked koulutusmahdollisuus if data is not found
https://jira.eduuni.fi/browse/OPHJOD-860
=> OPHJOD-860: Create routes and a placeholder page for education opportunity

src/components/OpportunityCard/OpportunityCard.tsx
Update OpportynityCard, especially for mobile
- Add type of card text
- Adjust paddings of the card; little smaller for mobile
- Adjust text styling
The checkbox+label is not right yet exactly like in the design, but left it like this for now to have bigger click area.
https://jira.eduuni.fi/browse/OPHJOD-865
=> OPHJOD-865: Update OpportunityCard layout for mobile

src/api/middlewares/resetTool.ts
* Fix API endpoint for suosikit to prevent resetting tool state after toggling an opportunity as a favorite.
https://jira.eduuni.fi/browse/OPHJOD-888
=> OPHJOD-888: Fix wrong api path in resetTool middleware

src/routes/Home/Home.tsx, src/routes/Profile/utils.tsx, src/routes/Tool/Competences.tsx, src/routes/Tool/Interests.tsx
- Fix helping tools content links in Tool/Competences&Interest
- Update `generateProfileLink` to support nested path with low effort
https://jira.eduuni.fi/browse/OPHJOD-891
=> OPHJOD-891: Fix helping tools content links in Tool/Competences&Interest

src/routes/Home/Home.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Root/Root.tsx, src/routes/Tool/Tool.tsx
- Tweak some views
https://jira.eduuni.fi/browse/OPHJOD-892
=> OPHJOD-892: Tweak some views

src/api/schema.d.ts, src/components/OpportunityCard/OpportunityCard.tsx, src/i18n/en/translation.json, src/routes/Tool/Tool.tsx, src/stores/useToolStore/index.ts
Show education opportunities at the same list with job opportunities. 
Note: Data of the opportunity is mock data with fixed ID, provided by the backend.
https://jira.eduuni.fi/browse/OPHJOD-859
=> OPHJOD-859: Show koulutusmahdollisuudet at the list of opportunities

src/components/LanguageMenu/LanguageMenu.tsx, src/routes/EducationOpportunity/Competences.tsx, src/routes/JobOpportunity/Competences.tsx, src/routes/JobOpportunity/Overview.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/CompetencesStep.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationStep.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/SummaryStep.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/utils.ts, src/routes/Profile/EducationHistory/modals/AddOrEditKoulutusModal.tsx, src/routes/Profile/EducationHistory/modals/EditKoulutuskokonaisuusModal.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/ActivityStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/CompetencesStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/SummaryStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/utils.ts, src/routes/Profile/FreeTimeActivities/modals/AddOrEditPatevyysModal.tsx, src/routes/Profile/FreeTimeActivities/modals/EditVapaaAjanToimintoModal.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/CompetencesStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/SummaryStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkplaceStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/utils.ts, src/routes/Profile/WorkHistory/modals/AddOrEditToimenkuvaModal.tsx, src/routes/Profile/WorkHistory/modals/EditTyonantajaModal.tsx, src/utils/index.ts
- Refactor localised values editing
https://jira.eduuni.fi/browse/OPHJOD-901
=> OPHJOD-901: Refactor localized values editing

src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/CompetencesStep.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationStep.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/SummaryStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/CompetencesStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/SummaryStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkplaceStep.tsx, src/routes/Profile/WorkHistory/modals/AddOrEditToimenkuvaModal.tsx, src/routes/Profile/WorkHistory/modals/EditTyonantajaModal.tsx
- Update some translations
https://jira.eduuni.fi/browse/OPHJOD-917
=> OPHJOD-917: Update some translations

tailwind.config.ts
- Update opacity of todo color
https://jira.eduuni.fi/browse/OPHJOD-930
=> OPHJOD-930: Update opacity of todo color

src/components/ExperienceTable/ExperienceTableRow.tsx
- Refactor ExperienceTableRow to use hyphenation
https://jira.eduuni.fi/browse/OPHJOD-929
=> OPHJOD-929: Refactor ExperienceTableRow to use hyphenation

src/components/OpportunityCard/OpportunityCard.tsx, src/i18n/fi/translation.json, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Tool/Tool.tsx, src/stores/useToolStore/index.ts
- Update opportunity card action buttons
- Update opportunity card compare to link
https://jira.eduuni.fi/browse/OPHJOD-OPHJOD-897
https://jira.eduuni.fi/browse/OPHJOD-OPHJOD-907
=> OPHJOD-897: Update opportunity card action buttons

src/i18n/fi/translation.json, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/Competences/constants.ts, src/routes/Profile/EducationHistory/EducationHistoryWizard/CompetencesStep.tsx, src/routes/Profile/EducationHistory/modals/AddOrEditKoulutusModal.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/CompetencesStep.tsx, src/routes/Profile/FreeTimeActivities/modals/AddOrEditPatevyysModal.tsx, src/routes/Profile/SomethingElse/EditMuuOsaaminenModal.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/CompetencesStep.tsx, src/routes/Profile/WorkHistory/modals/AddOrEditToimenkuvaModal.tsx
- Show  new add&edit buttons and arrow icon in profile/competences
- Remove button row from bottom of page
- Fix same translation being used multiple times
https://jira.eduuni.fi/browse/OPHJOD-856
NEW:
OLD
=> OPHJOD-856: Update competences -page to new design

index.html
- Add variant font for Poppins, instead of separate .ttf files.
- Update `@jod/design-system`
Remember to update the assets as instructed in the infra-repo to get the new fonts to your local environment.
https://jira.eduuni.fi/browse/OPHJOD-887
=> OPHJOD-887: Add variant font version for Poppins

src/api/schema.d.ts, src/components/OpportunityCard/OpportunityCard.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Tool/Tool.tsx, src/routes/Tool/utils.ts, src/routes/types.d.ts, src/stores/useSuosikitStore/index.ts, src/stores/useToolStore/index.ts
This change enables the favorite functionality of koulutusmahdollisuudet.
Toggle koulutusmahdolilisuus opportynity cards at tools.
Show koulutusmahdollisuus favorites at the the Favorites listing.
https://jira.eduuni.fi/browse/OPHJOD-862
=> OPHJOD-862: Enable koulutusmahdollisuus favorites

src/api/ammatit.ts, src/api/combinerImpl.ts, src/api/osaamiset.ts, src/api/schema.d.ts, src/index.css, src/routes/JobOpportunity/Overview.tsx, src/routes/JobOpportunity/loader.ts
Show occupation names in Työmahdollisuus
Needs https://github.com/Opetushallitus/jod-yksilo/pull/86
https://jira.eduuni.fi/browse/OPHJOD-900
=> OPHJOD-900: Show names for occupations

src/routes/Home/Home.tsx
- Use AVIF image in hero
https://jira.eduuni.fi/browse/OPHJOD-933
=> OPHJOD-933: Use AVIF image in hero

src/components/OpportunityCard/OpportunityCard.tsx
Fix excessive margins when match percent is not shown
https://jira.eduuni.fi/browse/OPHJOD-936
Before:
After:
=> OPHJOD-936: Fix excessive margins in opportunity card

src/i18n/fi/translation.json, src/routes/Profile/Favorites/Favorites.tsx, src/stores/useSuosikitStore/index.ts
- Fix the issue in Profile/Favorites where paging was not working correctly. 
- Pagination did not take selected filters into account.
- Fix the translations order
https://jira.eduuni.fi/browse/OPHJOD-983
=> OPHJOD-983: Fix Profile/Favorites paging issue

src/components/CompareTable/CompareCompetencesTable.tsx, src/components/CompareTable/CompareCompetencesTableRow.tsx, src/i18n/fi/translation.json, src/routes/JobOpportunity/Competences.tsx, src/routes/JobOpportunity/Overview.tsx, src/routes/JobOpportunity/loader.ts, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Tool/Tool.tsx, src/stores/useToolStore/index.ts
- Add comparison of competences
https://jira.eduuni.fi/browse/OPHJOD-899
=> OPHJOD-899: Add comparison of competences

src/components/MegaMenu/MegaMenu.tsx, src/components/NavigationBar/NavigationBar.tsx, src/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/components/UserButton/UserButton.tsx, src/routes/Root/Root.tsx
- Refactor navigation components
https://jira.eduuni.fi/browse/OPHJOD-985
=> OPHJOD-985: Refactor navigation components

src/components/ExperienceTable/ExperienceTable.tsx
- Remove empty table rows
https://jira.eduuni.fi/browse/OPHJOD-984
=> OPHJOD-984: Remove empty table rows

src/components/ExperienceTable/ExperienceTable.tsx, src/routes/Tool/Tool.tsx, src/stores/useToolStore/index.ts
Fixes bug in favorites state handling and data fetch.
https://jira.eduuni.fi/browse/OPHJOD-982
=> OPHJOD-982: Fix bug in favorites logic

package-lock.json, src/components/MainLayout/SimpleNavigationList.tsx, src/i18n/fi/translation.json, src/routes/EducationOpportunity/Competences.tsx, src/routes/EducationOpportunity/Overview.tsx, src/routes/JobOpportunity/Competences.tsx, src/routes/JobOpportunity/Overview.tsx, src/routes/Profile/Competences/Filters.tsx, src/routes/Tool/Competences.tsx, src/routes/Tool/Interests.tsx
- Update the use of Accordion component
- Refactor the use of Accordion in Profile/Competences filters to support screenreader better; including nested lists
- Remove the no longer used translation key/values
https://jira.eduuni.fi/browse/OPHJOD-952
=> OPHJOD-952: Update the use of Accordion component

package-lock.json
* Update DS to fix the issue that prevented clearing the datepicker value
* Tested the UI: Datepicker value can be cleared by clearing the the datepicker text input
https://jira.eduuni.fi/browse/OPHJOD-958
=> OPHJOD-958: Update DS to fix datepicker value clearing

package-lock.json, package.json
Update react-router & react-router-dom.
Related PR:s: #250, #251
https://jira.eduuni.fi/browse/OPHJOD-1003
https://jira.eduuni.fi/browse/OPHJOD-851
=> OPHJOD-1003: Update react-router & react-router-dom

src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/constants.ts, src/i18n/fi/translation.json, src/routes/Tool/Competences.tsx
* Added categorization to OsaamisSuosittelija
* Layout changes
https://jira.eduuni.fi/browse/OPHJOD-910
=> OPHJOD-910: Add categorization to OsaamisSuosittelija and update layout

src/routes/Tool/Tool.tsx
* Show less page buttons in tool pagination on mobile
https://jira.eduuni.fi/browse/OPHJOD-1029
Mobile:
Desktop:
=> OPHJOD-1029: Show less page buttons in tool pagination on mobile

index.html, package-lock.json
- Fix Poppins font
https://jira.eduuni.fi/browse/OPHJOD-1039
=> OPHJOD-1039: Fix Poppins font

src/routes/Tool/Competences.tsx, src/routes/Tool/Interests.tsx
- Fix export to profile logic
https://jira.eduuni.fi/browse/OPHJOD-1040
=> OPHJOD-1040: Fix export to profile logic

index.html, src/routes/Root/Root.tsx
- Add crossorigin attribute to favicon and manifest links
https://jira.eduuni.fi/browse/OPHJOD-1042
=> OPHJOD-1042: Add crossorigin attribute to favicon and manifest links

package-lock.json, src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx
- Add maxLength in OsaamisSuosittelija
https://jira.eduuni.fi/browse/OPHJOD-1045
=> OPHJOD-1045: Add maxLength in OsaamisSuosittelija

src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/i18n/fi/translation.json
- Remove duplicate competences in categories
https://jira.eduuni.fi/browse/OPHJOD-1046
=> OPHJOD-1046: Remove duplicate competences in categories

src/routes/JobOpportunity/JobOpportunity.tsx
* Add responsiveness to action bar in job opportunity page
https://jira.eduuni.fi/browse/OPHJOD-1051
=> OPHJOD-1051: Add responsiveness to action bar in job opportunity page

src/components/MainLayout/RoutesNavigationList.tsx
* Don't show active status for navigation items in RoutesNavigationList, if items are anchor links.
https://jira.eduuni.fi/browse/OPHJOD-1047
=> OPHJOD-1047: Remove active class from RoutesNavigationList for anchor links

package-lock.json, src/routes/Tool/Competences.tsx
* Update DS to fix a11y issues with Slider component
* Darker color for helping tool icon for "Muu osaaminen"
* AXE still reports a contrast issue with "Tyhjennä kaikki valitut osaamiset" button, but that's an issue with the DS button component with "gray-delete" variant. Will ask about this in the next PAMU session.
https://jira.eduuni.fi/browse/OPHJOD-1048
=> OPHJOD-1048: Fix accessability issues in tool

src/components/OpportunityCard/OpportunityCard.tsx
* Use different background color for match value for education opportunity in OpportunityCard component
https://jira.eduuni.fi/browse/OPHJOD-1059
=> OPHJOD-1059: Use different background color for match value for education opportunity in OpportunityCard component

src/api/schema.d.ts, src/i18n/fi/translation.json, src/routes/JobOpportunity/JobOpportunity.tsx
- Add professional group information visible to UI
- Updated schema
- Refactored the routes to make it more readable with less repetition
https://jira.eduuni.fi/browse/OPHJOD-1055
=> OPHJOD-1055: Add professional-group visible for job opportunities

src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/i18n/fi/translation.json, src/routes/Tool/Interests.tsx
- Add `mode` prop for OsaamisSuosittelija
- Use translations and colors based on this
- Add new translations related to interests
https://jira.eduuni.fi/browse/OPHJOD-1069
=> OPHJOD-1069: Update Interests part of the tool

README.md, src/api/client.ts, src/components/MainLayout/RoutesNavigationList.tsx, src/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/hooks/useLoginLink/index.ts, src/main.tsx, vite.config.ts
- Update base
https://jira.eduuni.fi/browse/OPHJOD-1053
=> OPHJOD-1053: Update base

src/routes/Root/Root.tsx
- Update logout path
https://jira.eduuni.fi/browse/OPHJOD-1053
=> OPHJOD-1053: Update logout path

src/components/LanguageMenu/LanguageMenu.tsx, src/components/MegaMenu/MegaMenu.tsx, src/components/NavigationBar/NavigationBar.test.tsx, src/components/NavigationBar/NavigationBar.tsx, src/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/components/OpportunityCard/OpportunityCard.tsx, src/components/UserButton/UserButton.tsx, src/hooks/useMenuClickHandler/index.ts, src/routes/Root/Root.tsx
Close menus when clicked outside of menu
https://jira.eduuni.fi/browse/OPHJOD-937
=> OPHJOD-937: Close popup menus if clicked outside of element

src/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/components/UserButton/UserButton.tsx
Update logout path for `UserButton`
Related to #265 where I missed the logout path change when I rebased.
https://jira.eduuni.fi/browse/OPHJOD-937
=> OPHJOD-937: Update logout path

src/i18n/fi/translation.json, src/routes/Tool/Tool.tsx, src/stores/useToolStore/index.ts
- Remove automatic loading feature
https://jira.eduuni.fi/browse/OPHJOD-1075
=> OPHJOD-1075: Remove automatic loading feature

src/hooks/useInitializeFilters/index.ts, src/i18n/fi/translation.json, src/routes/Profile/Competences/CompetenceFilters.tsx, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Competences/Filters.tsx, src/routes/Tool/Competences.tsx, src/routes/index.tsx, src/routes/types.d.ts
- Add competence import dialog for selecting what to import
- Refactored code here and there to have it more reusable and readable
- Add dialog for user that is not logged in; for import and export
https://jira.eduuni.fi/browse/OPHJOD-1078
=> OPHJOD-1078: Add competence import dialog for Tool + confirm dialogs

package-lock.json, src/routes/Tool/Goals.tsx
Update jod design-system to latest version
And use info icon with tooltip for selection cards mobile layout in goals view.
https://jira.eduuni.fi/browse/OPHJOD-1066
=> OPHJOD-1066: Use info icon in goals mobile layout

src/routes/Tool/Tool.tsx
- Make filter button sticky
https://jira.eduuni.fi/browse/OPHJOD-1068
=> OPHJOD-1068: Make filter button sticky

src/routes/JobOpportunity/JobOpportunity.tsx
* Try to fix `window.print` not working on some mobile devices. iOS Safari seems to have the most problems
* Don't use `onClick={window.print}` as this passes the click event data to window.print which might mess things up
* Don't use the return value from `window.print()` (https://stackoverflow.com/a/67709089)
* Hide the print button if `window.print` is not available
https://jira.eduuni.fi/browse/OPHJOD-1100
=> OPHJOD-1100: Fix print button not working on some mobile devices

package-lock.json
Update DS to fix floating checkboxes
https://jira.eduuni.fi/browse/OPHJOD-1092
Checkboxes stay in place as seen in this GIF
=> OPHJOD-1092: Update DS to fix floating checkboxes

src/routes/Tool/Tool.tsx
Close tool filters menu on outside click
https://jira.eduuni.fi/browse/OPHJOD-1110
=> OPHJOD-1110: Close tool filters menu on outside click

src/i18n/fi/translation.json, src/routes/JobOpportunity/JobOpportunity.tsx
- Update job opportunity
- Show job opportunity duties
https://jira.eduuni.fi/browse/OPHJOD-1098
https://jira.eduuni.fi/browse/OPHJOD-1097
=> OPHJOD-1097 & OPHJOD-1098

src/stores/useToolStore/index.ts
Use session storage instead of local storage. 
https://jira.eduuni.fi/browse/OPHJOD-1087
=> OPHJOD-1087: use session storage as tool store

src/routes/JobOpportunity/JobOpportunity.tsx
Use shared data between sections and navigation in job opportunity details page, so that content and navigation stays in sync
https://jira.eduuni.fi/browse/OPHJOD-1113
=> OPHJOD-1113: Use shared data between sections and navigation in job opportunity details page

src/routes/Root/Root.tsx
- Add max-w-full class to logos for responsive design
https://jira.eduuni.fi/browse/OPHJOD-1122
=> OPHJOD-1122: Add max-w-full class to logos for responsive design

package-lock.json, src/i18n/fi/translation.json, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/modals/AddOrEditKoulutusModal.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/FreeTimeActivities/modals/AddOrEditPatevyysModal.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx, src/routes/Profile/WorkHistory/modals/AddOrEditToimenkuvaModal.tsx
Update WizardProgress to use new and updated props.
https://jira.eduuni.fi/browse/OPHJOD-1089
=> OPHJOD-1089: Update WizardProgress for screenreader users

src/routes/Tool/OpportunitiesFilter.tsx
Change order of opportunity filters according the UX design.
https://jira.eduuni.fi/browse/OPHJOD-1134
=> OPHJOD-1134: Change opportunity filter order

src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/i18n/fi/translation.json, src/routes/Profile/Interests/EditKiinnostusModal.tsx
Update texts for interests under profile
https://jira.eduuni.fi/browse/OPHJOD-1144
=> OPHJOD-1144: Update texts for interests under profile

src/components/MegaMenu/MegaMenu.tsx, src/components/NavigationBar/NavigationBar.test.tsx, src/components/NavigationBar/NavigationBar.tsx, src/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/components/UserButton/UserButton.tsx, src/routes/Root/Root.tsx
- Fix the logout on mobile version
- Move logout form to Root
- Change NavigatonBar props a little to prevent prop drilling for LanguageButton and UserButton
https://jira.eduuni.fi/browse/OPHJOD-1135
=> OPHJOD-1135: Fix logout link on mobile

src/components/HelpingToolsContent/HelpingToolLinkItem.tsx, src/i18n/fi/translation.json, src/routes/Tool/Competences.tsx, src/routes/Tool/Interests.tsx, vite.config.ts
- Add link to Urataidot
https://jira.eduuni.fi/browse/OPHJOD-1137
=> OPHJOD-1137: Add link to Urataidot

src/components/MainLayout/RoutesNavigationList.tsx, src/components/UserButton/UserButton.tsx, src/hooks/useLoginLink/index.ts, src/i18n/fi/translation.json, src/routes/LandingPage/LandingPage.tsx, src/routes/Profile/index.ts, src/routes/Profile/utils.tsx, src/routes/index.tsx
Add landing page before login
https://jira.eduuni.fi/browse/OPHJOD-1074
=> OPHJOD-1074: Add landing page before login

src/routes/Root/loader.ts, src/routes/index.tsx
- Replace redirect with replace
https://jira.eduuni.fi/browse/OPHJOD-1156
=> OPHJOD-1156: Replace redirect with replace

src/hooks/useEnvironment/index.ts
Update the logic to recognize dev-environment.
Helps the case when e.g when testing with other devices than the current development machine, like phone or tablet in local environment.
https://jira.eduuni.fi/browse/OPHJOD-1162
=> OPHJOD-1162: Update logic to recognize dev-environment

src/api/osaamiset.test.ts, src/api/osaamiset.ts, src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/constants.ts, src/i18n/fi/translation.json, src/routes/Profile/Interests/Interests.tsx
- Add occupations for suggestions
https://jira.eduuni.fi/browse/OPHJOD-1125
=> OPHJOD-1125: Add occupations for suggestions

src/components/ExperienceTable/ExperienceTable.tsx, src/i18n/fi/translation.json, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationStep.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/SummaryStep.tsx, src/routes/Profile/EducationHistory/modals/AddOrEditKoulutusModal.tsx, src/routes/Profile/EducationHistory/modals/EditKoulutuskokonaisuusModal.tsx
- Update education history translations
https://jira.eduuni.fi/browse/OPHJOD-1165
=> OPHJOD-1165: Update education history translations

src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/i18n/fi/translation.json, src/routes/Profile/FreeTimeActivities/FreeTimeActivities.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/ActivityStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/CompetencesStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/SummaryStep.tsx, src/routes/Profile/FreeTimeActivities/modals/AddOrEditPatevyysModal.tsx, src/routes/Profile/FreeTimeActivities/modals/EditVapaaAjanToimintoModal.tsx
- Update free time activities translations
https://jira.eduuni.fi/browse/OPHJOD-1170
=> OPHJOD-1170: Update free time activities translations

package-lock.json, src/i18n/fi/translation.json, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationStep.tsx, src/routes/Profile/EducationHistory/modals/AddOrEditKoulutusModal.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/ActivityStep.tsx, src/routes/Profile/FreeTimeActivities/modals/AddOrEditPatevyysModal.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkplaceStep.tsx, src/routes/Profile/WorkHistory/modals/AddOrEditToimenkuvaModal.tsx, src/utils/index.ts
- Add datepicker translations
https://jira.eduuni.fi/browse/OPHJOD-1177
=> OPHJOD-1177: Add datepicker translations

src/api/schema.d.ts, src/i18n/fi/translation.json, src/routes/Tool/Competences.tsx, src/routes/Tool/Goals.tsx, src/routes/Tool/Interests.tsx, src/routes/Tool/Restrictions.tsx, src/routes/Tool/Tool.tsx
- Add virtual assistant
https://jira.eduuni.fi/browse/OPHJOD-1143
=> OPHJOD-1143: Add virtual assistant

src/components/MegaMenu/MegaMenu.tsx, src/components/UserButton/UserButton.tsx
Mega/header menu did not close on mobile when user icon was clicked. Now it's fixed. 
https://jira.eduuni.fi/browse/OPHJOD-1161
=> OPHJOD-1161: Fix mega menu not closing on mobile when user icon clicked

src/i18n/fi/translation.json, src/routes/Tool/Goals.tsx
Update the tooltip texts tool goals.
https://jira.eduuni.fi/browse/OPHJOD-966
=> OPHJOD-966: Update texts for goals

src/i18n/fi/translation.json
Updated the description text under profile "interests" and "something else".
https://jira.eduuni.fi/browse/OPHJOD-1173
https://jira.eduuni.fi/browse/OPHJOD-1174
=> OPHJOD-1173 & OPHJOD-1174: Update description texts under profile

package-lock.json, src/routes/Tool/Goals.tsx
* Update DS
* Add tooltip handling to goals. Only 1 tooltip can be visible.
https://jira.eduuni.fi/browse/OPHJOD-1154
=> OPHJOD-1154: Update DS and change tooltip logic in goals

package-lock.json, package.json, src/components/FormError/FormError.test.tsx, src/components/FormError/FormError.tsx, src/components/FormError/TouchedFormError.tsx, src/components/index.tsx, src/constants.ts, src/i18n/fi/translation.json, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationStep.tsx, src/routes/Profile/EducationHistory/modals/AddOrEditKoulutusModal.tsx, src/routes/Profile/EducationHistory/modals/EditKoulutuskokonaisuusModal.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/ActivityStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/FreeTimeActivities/modals/AddOrEditPatevyysModal.tsx, src/routes/Profile/FreeTimeActivities/modals/EditVapaaAjanToimintoModal.tsx, src/routes/Profile/Interests/EditKiinnostusModal.tsx, src/routes/Profile/SomethingElse/EditMuuOsaaminenModal.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkplaceStep.tsx, src/routes/Profile/WorkHistory/modals/AddOrEditToimenkuvaModal.tsx, src/routes/Profile/WorkHistory/modals/EditTyonantajaModal.tsx, src/utils/index.ts
* Implemented form validation
https://jira.eduuni.fi/browse/OPHJOD-1049
=> OPHJOD-1049: Implement form validation

src/i18n/fi/translation.json
Fix typos and errors in translations. 
```
Kartoita tilanteesi
Vanha: Alla on työkalut joiden avulla syötän tietojasi joiden perusteella tarjoamme sinulle mahdollisuuksia oikealla.
Uusi: Mitä osaat ja mistä olet kiinnostunut? Kokeile erilaisia kartoitustyökalujamme, jolla voit kartoittaa omaa tilannettasi!
Mahdollisuutesi
Vanha: Alla näet palvelun tunnistamia työ- ja koulutusmahdollisuuksia tietojesi pohjalta.
Uusi: Tutki erilaisia työ- ja koulutusmahdollisuuksia. Voit myös testata miten kartoittamasi tiedot vaikuttavat esitettäviin mahdollisuuksiin.
```
https://jira.eduuni.fi/browse/OPHJOD-1095
=> OPHJOD-1095: Fix typos and errors in translations

package-lock.json
Update `@jod/design-system` to have fixed DatePicker
https://jira.eduuni.fi/browse/OPHJOD-1238
=> OPHJOD-1238: Update @jod/design-system

src/routes/EducationOpportunity/loader.ts, src/routes/JobOpportunity/loader.ts, src/routes/Profile/Competences/loader.ts, src/routes/Tool/Tool.tsx, src/routes/Tool/loader.ts, src/stores/useToolStore/index.ts
- Fix not logged in user data fetching logic
https://jira.eduuni.fi/browse/OPHJOD-1246
=> OPHJOD-1246: Fix not logged in user data fetching logic

src/routes/Tool/Interests.tsx
- Show development-only system prompt for virtual assistant
https://jira.eduuni.fi/browse/OPHJOD-1224
=> OPHJOD-1224: Show development-only system prompt for virtual assistant

src/routes/Tool/Interests.tsx, src/routes/Tool/Tool.tsx, src/routes/Tool/VirtualAssistant.tsx, src/stores/useToolStore/index.ts
- Update VirtualAssistant layout
- Move the VirtualAssistant to it's own file
Mobile especially is not exactly like in the design; most notably not taking the whole screen. But by leaving the margins around the chat is more consistent with the design in overall.
And based on the design it looked like it would be a modal and therefore blocking the scrolling of the page to other content --> using in a different way than the desktop.
Now it feels that desktop and mobile experience is closer to each other.
https://jira.eduuni.fi/browse/OPHJOD-1255
=> OPHJOD-1255: Update VirtualAssistant layout

src/routes/Tool/Tool.tsx
- Focus first element of list after page change
https://jira.eduuni.fi/browse/OPHJOD-1244
=> OPHJOD-1244: Focus first element of list after page change

src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/MyGoals/AddGoalModal.tsx, src/stores/useSuosikitStore/index.ts
Fix unwanted scrolling in Goals: move `window.scrollTo` from store to UI-side in favorites
https://jira.eduuni.fi/browse/OPHJOD-1275
=> OPHJOD-1275: Move window.scrollTo to UI-side in favorites

src/components/MobileFilterButton/MobileFilterButton.tsx, src/i18n/fi/translation.json, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Favorites/Favorites.tsx
Update Favorites page to show filters also on mobile 
https://jira.eduuni.fi/browse/OPHJOD-1283
=> OPHJOD-1283: Update Favorites page to show filters also on mobile

src/components/ExperienceTable/ExperienceTable.tsx, src/components/ExperienceTable/ExperienceTableRow.tsx, src/i18n/fi/translation.json, src/routes/Tool/Tool.tsx
- Fix overflow bug
https://jira.eduuni.fi/browse/OPHJOD-1318
=> OPHJOD-1318: Make some small tweaks

src/routes/Tool/ToolOpportunityCardActionMenu.tsx
- Fix routing in ToolOpportunityCardActionMenu
https://jira.eduuni.fi/browse/OPHJOD-1211
=> OPHJOD-1211: Fix routing in ToolOpportunityCardActionMenu

package-lock.json, package.json, src/api/middlewares/toast.ts, src/components/Toaster/Toaster.tsx
Update `react-hot-toast`
With the update the `toast.message`  was typed differently and the message can be also something else than string. But in our case it is now always string. Therefore filtering only to show messages which are string --> `safeToasts`
https://jira.eduuni.fi/browse/OPHJOD-1313
https://jira.eduuni.fi/browse/OPHJOD-851
=> OPHJOD-1313: Update react-hot-toast

package-lock.json, package.json, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/utils.ts, src/routes/Profile/EducationHistory/modals/AddOrEditKoulutusModal.tsx, src/routes/Profile/EducationHistory/modals/EditKoulutuskokonaisuusModal.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/utils.ts, src/routes/Profile/FreeTimeActivities/modals/AddOrEditPatevyysModal.tsx, src/routes/Profile/FreeTimeActivities/modals/EditVapaaAjanToimintoModal.tsx, src/routes/Profile/Interests/EditKiinnostusModal.tsx, src/routes/Profile/SomethingElse/EditMuuOsaaminenModal.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/utils.ts, src/routes/Profile/WorkHistory/modals/AddOrEditToimenkuvaModal.tsx, src/routes/Profile/WorkHistory/modals/EditTyonantajaModal.tsx
Update `@hookform/resolvers` and make changes to get rid of errors after update
- Multiple places had the `id` as required but it type was `string|undefined`. Coming from the API-schema.
- Multiple places had the `loppuPvm` as required when it was actually optional.
- `nimi` & `kuvaus` were missing from multiple places.
https://jira.eduuni.fi/browse/OPHJOD-1313
https://jira.eduuni.fi/browse/OPHJOD-851
=> OPHJOD-1313: Update hookform/resolvers

package-lock.json, package.json
- Update `@jod/design-system`
- and other dependencies that got updates after the previous update
There was some style issues on the development environment and it seems that updating the DS fixed that.
Updated other depedencies again while at it.
https://jira.eduuni.fi/browse/OPHJOD-1313
https://jira.eduuni.fi/browse/OPHJOD-851
=> OPHJOD-1313: Update jod-design-system and other dependencies

src/api/schema.d.ts, src/auth/auth.ts, src/i18n/fi/translation.json, src/main.tsx, src/routes/Introduction/Introduction.tsx, src/routes/Introduction/index.ts, src/routes/index.tsx
- Add introduction flow for new users
https://jira.eduuni.fi/browse/OPHJOD-1131
=> OPHJOD-1131: Add introduction flow for new users

package-lock.json, src/hooks/useEscHandler/index.ts
- Update to use `ds-modal` as identifier for the Modals used in escHandler logic
- _Update `@jod/design-system`_*
\* **As draft as it requires Opetushallitus/jod-design-system/pull/235 to be merged first to have it here in use.**
https://jira.eduuni.fi/browse/OPHJOD-1356
=> OPHJOD-1356: Update escHandler to check only ds-modal's id

package-lock.json, src/hooks/useEscHandler/index.ts, src/routes/Profile/EducationHistory/modals/ImportKoulutusSummaryModal.tsx, src/routes/Tool/Interests.tsx, src/routes/Tool/VirtualAssistant.tsx
- Fix screen reader not reading Valitut kiinnostukset view. To access it from menu: Valikko -> Mikä minua kiinnostaa -> Keskusteleva kiinnostusten kartoitus -> Kiinnostukset (2) -> the actual view
- Fix screen reader not reading Kiinnostusten kartoitus view. To access it from menu: Valikko -> Mikä minua kiinnostaa -> Keskusteleva kiinnostusten kartoitus -> the actual view
- Fix dialog/modal/form not getting close by esc-key press. Model/Dialog/Form that uses React.useId(); (their id starts with : and ends with :) can be now close with ESC-key.
https://jira.eduuni.fi/browse/OPHJOD-1300
=> OPHJOD-1300: Fix screen reader read and dialog close issue

src/api/schema.d.ts, src/routes/Profile/EducationHistory/modals/ImportKoulutusSummaryModal.tsx
- Add multiple koulutuskokonaisuudet once from Koski
https://jira.eduuni.fi/browse/OPHJOD-1330
=> OPHJOD-1330: Add multiple koulutuskokonaisuudet once from Koski

src/api/schema.d.ts, src/components/ExperienceTable/ExperienceTableRow.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/utils.ts, src/routes/Profile/EducationHistory/modals/AddOrEditKoulutusModal.tsx, src/routes/Profile/EducationHistory/modals/ImportKoulutusSummaryModal.tsx, src/routes/Profile/EducationHistory/utils.ts, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx
- Make 'alkuPvm' optional
https://jira.eduuni.fi/browse/OPHJOD-1380
=> OPHJOD-1380: Make 'alkuPvm' optional

src/i18n/fi/translation.json, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Tool/Tool.tsx
- Add guidance texts and useful links to the 'Favorites' page to improve user navigation and understanding.
https://jira.eduuni.fi/browse/OPHJOD-1367
=> OPHJOD-1367: Add guidance texts and links to 'Favorites' page

package-lock.json, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/ActivityStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkplaceStep.tsx
- Update form validation
- Fix missing date check validation from free-time activities
- Update `@jod/design-system` as it complained about the missing refs
Original issue was pretty much solved in another ticket before this, so this has only the changes to improve the form validation here and there.
https://jira.eduuni.fi/browse/OPHJOD-1351
=> OPHJOD-1351: Update form validating

src/components/DeletePolkuButton/DeletePolkuButton.tsx, src/routes/Profile/MyGoals/MyGoalsSection.tsx, src/routes/Profile/Path/Path.tsx
* Fixed an oversight where a deleted polku would still be present in the UI in "päämääräni" page
* Created a shared "DeletePolkuButton" that is used in "päämäräni" and "polkuni" page to avoid code duplication
https://jira.eduuni.fi/browse/OPHJOD-1414
=> OPHJOD-1414: Remove polku from UI after delete is successful

src/i18n/fi/translation.json, src/routes/JobOpportunity/JobOpportunity.tsx, src/routes/JobOpportunity/loader.ts, src/routes/types.d.ts, src/utils/codes/codes.ts, src/utils/codes/kunta_fi.json, src/utils/codes/maa_fi.json, src/utils/codes/maakunta_fi.json, src/utils/codes/tyokieli_fi.json, src/utils/index.test.ts, src/utils/index.ts
* MVP for displaying additional Jakauma information in job opportunity page
https://jira.eduuni.fi/browse/OPHJOD-1358
=> OPHJOD-1358: MVP for displaying jakauma info in job opportunity page

src/components/MegaMenu/MegaMenu.tsx, src/hooks/useAppRoutes/index.ts, src/i18n/fi/translation.json, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivities.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/MyGoals/MyGoals.tsx, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Profile/ProfileFront/ProfileFront.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/routes/Profile/WorkHistory/WorkHistory.tsx, src/routes/Profile/components/index.tsx, src/routes/index.tsx
- Add front page for profile
- Preferences page contains Lorem ipsum for now.
- Refactored the Profile's side navigation to decrease repetition
https://jira.eduuni.fi/browse/OPHJOD-1387
=> OPHJOD-1387: Add Profile front page

src/components/UserButton/UserButton.tsx, src/routes/LandingPage/LandingPage.tsx
Update the callback url to take to new profile front page.
https://jira.eduuni.fi/browse/OPHJOD-1387
=> OPHJOD-1387: Update login callback url to profile front

package-lock.json, src/routes/Profile/Path/modal/VaiheModal.tsx
* Update DS
* Use the new `fullWidthContent` prop in VaiheModal
https://jira.eduuni.fi/browse/OPHJOD-1339
=> OPHJOD-1339: Update DS and use fullWidthContent prop in VaiheModal

package-lock.json, src/components/LoginModal/LoginModal.tsx, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/modals/AddOrEditKoulutusModal.tsx, src/routes/Profile/EducationHistory/modals/EditKoulutuskokonaisuusModal.tsx, src/routes/Profile/EducationHistory/modals/ImportKoulutusResultModal.tsx, src/routes/Profile/EducationHistory/modals/ImportKoulutusStartModal.tsx, src/routes/Profile/EducationHistory/modals/ImportKoulutusSummaryModal.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/FreeTimeActivities/modals/AddOrEditPatevyysModal.tsx, src/routes/Profile/FreeTimeActivities/modals/EditVapaaAjanToimintoModal.tsx, src/routes/Profile/Interests/EditKiinnostusModal.tsx, src/routes/Profile/MyGoals/AddGoalModal.tsx, src/routes/Profile/Path/modal/VaiheModal.tsx, src/routes/Profile/SomethingElse/EditMuuOsaaminenModal.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx, src/routes/Profile/WorkHistory/modals/AddOrEditToimenkuvaModal.tsx, src/routes/Profile/WorkHistory/modals/EditTyonantajaModal.tsx, src/routes/Tool/Competences.tsx
- Refactor modal footers
https://jira.eduuni.fi/browse/OPHJOD-1422
=> OPHJOD-1422: Refactor modal footers

.github/workflows/build.yml
Disable e2e tests by commenting them out in build workflow file
https://jira.eduuni.fi/browse/OPHJOD-1418
=> OPHJOD-1418: Disable e2e tests

src/components/ExperienceTable/ExperienceTable.tsx, src/components/ExperienceTable/ExperienceTableRow.tsx, src/components/MainLayout/MainLayout.tsx
- Refactor ExperienceTable layout
https://jira.eduuni.fi/browse/OPHJOD-1424
=> OPHJOD-1424: Refactor ExperienceTable layout

src/components/MoreActionsDropdown/MoreActionsDropdown.tsx, src/hooks/useInteractionMethod/index.ts, src/routes/Root/Root.tsx, src/routes/Tool/Tool.tsx
Close popup menus when navigating with keyboard. Fixed this problem
https://jira.eduuni.fi/browse/OPHJOD-1296
=> OPHJOD-1296: Close popup menus when navigating with keyboard

package-lock.json, src/components/LoginModal/LoginModal.tsx, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/modals/AddOrEditKoulutusModal.tsx, src/routes/Profile/EducationHistory/modals/ImportKoulutusResultModal.tsx, src/routes/Profile/EducationHistory/modals/ImportKoulutusStartModal.tsx, src/routes/Profile/EducationHistory/modals/ImportKoulutusSummaryModal.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/FreeTimeActivities/modals/AddOrEditPatevyysModal.tsx, src/routes/Profile/FreeTimeActivities/modals/EditVapaaAjanToimintoModal.tsx, src/routes/Profile/Interests/EditKiinnostusModal.tsx, src/routes/Profile/MyGoals/AddGoalModal.tsx, src/routes/Profile/Path/modal/VaiheModal.tsx, src/routes/Profile/SomethingElse/EditMuuOsaaminenModal.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx, src/routes/Profile/WorkHistory/modals/AddOrEditToimenkuvaModal.tsx, src/routes/Profile/WorkHistory/modals/EditTyonantajaModal.tsx, src/routes/Tool/Competences.tsx
- Add whitespace-nowrap class to modal buttons
https://jira.eduuni.fi/browse/OPHJOD-1442
=> OPHJOD-1442: Add whitespace-nowrap class to modal buttons

package-lock.json, src/components/AiInfo/AiInfo.tsx, src/components/OpportunityDetails/OpportunityDetails.tsx, src/components/ScrollHeading/ScrollHeading.tsx, src/components/index.tsx, src/i18n/fi/translation.json, src/routes/EducationOpportunity/EducationOpportunity.tsx, src/routes/JobOpportunity/JobOpportunity.tsx
* Added AI info button to opportunity pages
https://jira.eduuni.fi/browse/OPHJOD-1331
=> OPHJOD-1331: Add AI info button to opportunity pages

src/routes/Profile/MyGoals/MyGoalsSection.tsx
* Polku/suunnitelma is now removed from the UI after delete API call succeedes
* NOTE: This was previously fixed but the issue appeared again after some changes
https://jira.eduuni.fi/browse/OPHJOD-1481
https://jira.eduuni.fi/browse/OPHJOD-1414
=> OPHJOD-1481: Remove polku from UI after deletion

src/i18n/fi/translation.json, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Profile/ProfileFront/ProfileFront.tsx
- Move profile deletion to preferences
https://jira.eduuni.fi/browse/OPHJOD-1461
=> OPHJOD-1461: Move profile deletion to preferences

src/routes/Profile/Preferences/Preferences.tsx, src/routes/Profile/ProfileFront/ProfileFront.tsx, src/routes/Root/Root.tsx, src/routes/Root/index.ts
- Add LogoutFormContext
https://jira.eduuni.fi/browse/OPHJOD-1456
=> OPHJOD-1456: Add LogoutFormContext

src/i18n/fi/translation.json, src/routes/Profile/Preferences/Preferences.tsx
- Add download link for profile data
https://jira.eduuni.fi/browse/OPHJOD-1463
=> OPHJOD-1463: Add download link for profile data

src/api/schema.d.ts, src/routes/Profile/EducationHistory/EducationHistory.tsx
Add polling mechanism for osaamiset tunnistus.
https://jira.eduuni.fi/browse/OPHJOD-1449
=> OPHJOD-1449: Add polling mechanism for osaamiset tunnistus

package-lock.json
- Updated the `jod/design-system` dependency version to include enhancements and fixes for the `Tag` component.
https://jira.eduuni.fi/browse/OPHJOD-1451
=> OPHJOD-1451: Update jod/design-system to include Tag component changes

src/i18n/fi/translation.json
- Update translations
https://jira.eduuni.fi/browse/OPHJOD-1518
=> OPHJOD-1518: Update translations

src/routes/Profile/MyGoals/MyGoalsSection.tsx
- Enable path creation exclusively for work opportunities
https://jira.eduuni.fi/browse/OPHJOD-1508
=> OPHJOD-1508: Enable path creation exclusively for work opportunities

src/components/NavMenu/NavMenu.tsx, src/routes/index.tsx
- Refactor NavMenu and update routing structure
https://jira.eduuni.fi/browse/OPHJOD-1532
=> OPHJOD-1532: Refactor NavMenu and update routing structure

package-lock.json, src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/i18n/fi/translation.json, src/routes/Profile/EducationHistory/EducationHistoryWizard/CompetencesStep.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationHistoryWizard.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/EducationStep.tsx, src/routes/Profile/EducationHistory/EducationHistoryWizard/SummaryStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/ActivityStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/CompetencesStep.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/FreeTimeActivitiesWizard.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivitiesWizard/SummaryStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/CompetencesStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/SummaryStep.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkHistoryWizard.tsx, src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkplaceStep.tsx
- Update Modals in `profile/*` paths
- modal content to take full width
- Change used tokens
- Adjust margins/paddings
- Show icon in next-button also in desktop
- Add new translations
https://jira.eduuni.fi/browse/OPHJOD-1496
=> OPHJOD-1496: Update Modal layouts

src/api/schema.d.ts, src/components/OpportunityDetails/OpportunityDetails.tsx, src/routes/Tool/Tool.tsx, src/stores/useSuosikitStore/index.ts, src/stores/useToolStore/index.ts
- Rename suosionKohdeId to kohdeId
https://jira.eduuni.fi/browse/OPHJOD-1535
=> OPHJOD-1535: Rename suosionKohdeId to kohdeId

src/components/NavMenu/menuRoutes.tsx
- Add active for navigation menu
https://jira.eduuni.fi/browse/OPHJOD-1539
=> OPHJOD-1539: Add active for navigation menu

src/routes/Tool/Tool.tsx
Fix text token used in Kohtaanto tabs
- mobile tokens no longer exists for `button-*` tokens
https://jira.eduuni.fi/browse/OPHJOD-1547
=> OPHJOD-1547: Fix text token used in Kohtaanto tabs

package-lock.json
Update `@jod/design-system` to the latest available.
https://jira.eduuni.fi/browse/OPHJOD-1547
=> OPHJOD-1547: Update @jod/design-system

package-lock.json, src/components/NavMenu/NavMenu.tsx, src/components/NavMenu/menuRoutes.tsx
- Remove unused tool routes
https://jira.eduuni.fi/browse/OPHJOD-1540
=> OPHJOD-1540: Remove unused tool routes

src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivities.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/routes/Profile/WorkHistory/WorkHistory.tsx
The following updates were made:
- Added competence-specific icons to grouped sources. Menu: Omat sivuni -> Osaamiseni
- Added lightbulb icon to "Muut osaamiseni" title. Menu: Omat sivuni -> Osaamiseni -> Muut osaamiseni
- Added school icon to "Koulutukseni" title. Menu: Omat sivuni -> Osaamiseni -> Koulutukseni
- Added work icon to "Työpaikkani" title. Menu: Omat sivuni -> Osaamiseni -> Työpaikkani
- Added sailing icon to "Vapaa-ajan toimintoni" title. Menu: Omat sivuni -> Osaamiseni -> Vapaa-ajan toimintoni
https://jira.eduuni.fi/browse/OPHJOD-1557
=> OPHJOD-1557: Add type icons to titles in and under Osaamiseni

package-lock.json, src/components/LanguageButton/LanguageButton.tsx, src/components/LanguageMenu/LanguageMenu.tsx, src/components/UserButton/UserButton.tsx, src/routes/Root/Root.tsx
- Use updated NavigationBar
https://jira.eduuni.fi/browse/OPHJOD-1527
=> OPHJOD-1527: Use updated NavigationBar

src/components/NavMenu/NavMenu.tsx, src/i18n/fi/translation.json
- Refactor external link sections in NavMenu
https://jira.eduuni.fi/browse/OPHJOD-1573
=> OPHJOD-1573: Refactor external link sections in NavMenu

src/components/LanguageButton/LanguageButton.tsx, src/components/UserButton/UserButton.tsx
- Remove redundant ds classes
https://jira.eduuni.fi/browse/OPHJOD-1527
=> OPHJOD-1527: Remove redundant ds classes

src/components/LanguageButton/LanguageButton.tsx, src/components/UserButton/UserButton.tsx
- Fix caret icons
https://jira.eduuni.fi/browse/OPHJOD-1527
=> OPHJOD-1527: Fix caret icons

src/routes/Profile/Path/Path.tsx, src/routes/Profile/Path/VaiheCard.tsx
Update Path layout to work little better on mobile
- Designs still not available, but now it is possible to use it a little better
https://jira.eduuni.fi/browse/OPHJOD-1444
=> OPHJOD-1444: Update Path layout to better support mobile

src/components/MobileFilterButton/MobileFilterButton.tsx, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/MyGoals/AddGoalModal.tsx, src/routes/Tool/Tool.tsx
* Fix filter buttons not appearing in mobile view. They were actually visible when screen was below `sm` size, but they needed to be visible in `md` too
* Renamed the `breakpoint` prop to `hideAfterBreakpoint` for clarity
https://jira.eduuni.fi/browse/OPHJOD-1567
=> OPHJOD-1567: Fix disappearing mobile filter buttons in profile

src/routes/Profile/Path/components/DurationFormSection.tsx, src/routes/Profile/Path/modal/ManualVaiheModal/DetailsStep.tsx, src/routes/Profile/Path/utils.ts
Add required check to end date. End date is mandatory in backend.
https://jira.eduuni.fi/browse/OPHJOD-1531
=> OPHJOD-1531: Add required check to end date

src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/Home/Home.tsx
Updated the home page to match latest design
https://jira.eduuni.fi/browse/OPHJOD-1582
**Desktop**
**Mobile** (Note: Screenshot does not show the padding on right side for some reason, but it's there)
=> OPHJOD-1582: Update home page

eslint.config.js, package-lock.json, src/components/NavMenu/NavMenu.tsx, src/i18n/fi/translation.json, src/index.css, src/routes/Root/Root.tsx, src/routes/Tool/Competences.tsx
- Add extra section to NavMenu
https://jira.eduuni.fi/browse/OPHJOD-1592
=> OPHJOD-1592: Add extra section to NavMenu

src/routes/Profile/MyGoals/AddGoalModal.tsx, src/routes/Profile/MyGoals/loader.ts, src/routes/Profile/Path/Path.tsx
* Populate path competences from profile. Competences are always in sync with profile and they cannot be ignored or unchecked.
* Cleaned up the code a bit
https://jira.eduuni.fi/browse/OPHJOD-1608
=> OPHJOD-1608: Populate path competences from profile and disable them

src/routes/Tool/CategorizedCompetenceTagList.tsx, src/routes/Tool/Tool.tsx
- Update logic for value calculation
https://jira.eduuni.fi/browse/OPHJOD-1651
=> OPHJOD-1651: Update logic for value calculation

src/routes/Home/Home.tsx, src/routes/Tool/AdditionalSupport.tsx
* Swapped the action buttons for 2 hero cards in `Home` route.
* Added links to "Osaamispolun palveluhakemisto".
https://jira.eduuni.fi/browse/OPHJOD-1649
=> OPHJOD-1649: Home page button swap and add links to service directory

src/routes/Profile/Interests/EditKiinnostusModal.tsx, src/routes/Profile/SomethingElse/EditMuuOsaaminenModal.tsx
- Fix EditInterestModal and EditMuuOsaaminenModal
https://jira.eduuni.fi/browse/OPHJOD-1646
=> OPHJOD-1646: Fix EditInterestModal and EditMuuOsaaminenModal

src/components/Chatbot/Chatbot.tsx, src/components/Chatbot/loadAiAgentFloat.ts, src/components/index.tsx, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/Root/Root.tsx
- Add Chatbot PoC
https://jira.eduuni.fi/browse/OPHJOD-1675
=> OPHJOD-1675: Add Chatbot PoC

src/i18n/config.ts
Fix "På sverige" -> "På svenska"
https://jira.eduuni.fi/browse/OPHJOD-1676
=> OPHJOD-1676: Fix language menu string

src/api/schema.d.ts, src/routes/Profile/Path/VaiheCard.tsx, src/routes/Profile/Path/modal/ProposeVaiheModal/ProposeVaiheModal.tsx, src/routes/Profile/Path/utils.ts
- Add mahdollisuusId to Vaihe
https://jira.eduuni.fi/browse/OPHJOD-1553
=> OPHJOD-1553: Add mahdollisuusId to Vaihe

src/routes/Profile/Path/Path.tsx
- Fix percentage calculation to handle division by zero
https://jira.eduuni.fi/browse/OPHJOD-1701
=> OPHJOD-1701: Fix percentage calculation to handle division by zero

package-lock.json, src/routes/Profile/Path/modal/ProposeVaiheModal/VaiheOpportunityCard.tsx, src/routes/Tool/OpportunitiesSorting.tsx
Update usage of RadioButton
https://jira.eduuni.fi/browse/OPHJOD-1678
=> OPHJOD-1678: Update RadioButton usage

package-lock.json, src/components/ExperienceTable/ExperienceTableRow.tsx, src/components/HelpingToolsContent/HelpingToolLinkItem.tsx, src/components/OpportunityCard/OpportunityCard.tsx, src/routes/Profile/MyGoals/MyGoalsSection.tsx, src/routes/Profile/Path/Path.tsx, src/routes/Profile/Path/VaiheCard.tsx, src/routes/Profile/Path/modal/ManualVaiheModal/CompetencesStep.tsx, src/routes/Tool/Tool.tsx
- Refactor color variables
https://jira.eduuni.fi/browse/OPHJOD-1702
=> OPHJOD-1702: Refactor color variables

src/i18n/fi/translation.json, src/routes/Profile/ProfileFront/ProfileFront.tsx
- Update profile preferences translations
https://jira.eduuni.fi/browse/OPHJOD-1711
=> OPHJOD-1711: Update profile preferences translations

src/i18n/fi/translation.json, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Profile/ProfileFront/ProfileFront.tsx
- Update translations and improve text styling
https://jira.eduuni.fi/browse/OPHJOD-1709
=> OPHJOD-1709: Update translations and improve text styling

src/hooks/useInitializeFilters/index.ts, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/Competences/loader.ts
- Add support for free-text skills in competences
https://jira.eduuni.fi/browse/OPHJOD-1747
=> OPHJOD-1747: Add support for free-text skills in competences

src/components/CompareTable/CompareCompetencesTable.tsx
- Fix button visibility
https://jira.eduuni.fi/browse/OPHJOD-1704
=> OPHJOD-1704: Fix button visibility

src/components/CompareTable/CompareCompetencesTableRow.tsx
- Replace MdCheck icon with styled div
https://jira.eduuni.fi/browse/OPHJOD-1703
=> OPHJOD-1703: Replace MdCheck icon with styled div

package-lock.json, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Root/Root.tsx
- Add MatomoTracker
https://jira.eduuni.fi/browse/OPHJOD-1687
=> OPHJOD-1687: Add MatomoTracker

src/routes/Tool/CategorizedCompetenceTagList.tsx
Fix removing of interests in tool not working
https://jira.eduuni.fi/browse/OPHJOD-1761
=> OPHJOD-1761: Fix removing of interests in tool not working

package-lock.json, src/api/schema.d.ts, src/components/MoreActionsDropdown/MoreActionsDropdown.tsx, src/components/OpportunityCard/OpportunityCard.tsx, src/i18n/fi/translation.json, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/MyGoals/AddGoalModal.tsx, src/routes/Profile/MyGoals/MyGoalsSection.tsx, src/routes/Profile/MyGoals/loader.ts, src/routes/Profile/Path/Path.tsx, src/routes/Profile/Path/loader.ts, src/routes/Root/Root.tsx, src/routes/Tool/Tool.tsx, src/routes/types.d.ts, src/stores/usePolutStore/index.ts, src/stores/useSuosikitStore/index.ts, src/stores/useToolStore/index.ts
* Update `OpportunityCard` component to match latest design
* Show `ammattiryhma` on the card if data is available
https://jira.eduuni.fi/browse/OPHJOD-1727
**Desktop**
**Mobile**
=> OPHJOD-1727: Update OpportunityCard to match latest design

src/i18n/fi/translation.json, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivities.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/MyGoals/MyGoals.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/routes/Profile/WorkHistory/WorkHistory.tsx
Add `EmptyState` component to use in several places.
**Commits are separated for now, idea is to merge them to just one commit before merging.**
https://jira.eduuni.fi/browse/OPHJOD-1785
=> OPHJOD-1785: Add EmptyState to use

package-lock.json, src/components/ExperienceTable/ExperienceTable.tsx, src/hooks/useInitializeFilters/index.ts, src/i18n/fi/translation.json, src/routes/Profile/Competences/CompetenceFilters.tsx, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/Competences/GroupByAlphabet.tsx, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/Competences/constants.ts, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivities.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/MyGoals/MyGoals.tsx, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/routes/Profile/WorkHistory/WorkHistory.tsx, src/routes/Profile/components/ProfileNavigationList.tsx, src/routes/Profile/components/ProfileSectionTitle.tsx, src/routes/Profile/components/index.tsx, src/routes/Profile/utils.tsx
Updated the profile pages to match latest design
https://jira.eduuni.fi/browse/OPHJOD-1797
=> OPHJOD-1797: Update profile page to match latest design

package-lock.json
- Update jod-design-system dependency
https://jira.eduuni.fi/browse/OPHJOD-1688
=> OPHJOD-1688: Update jod-design-system dependency

.github/workflows/build.yml, .nvmrc, package-lock.json, package.json
- Update Node.js version to lts/jod
https://jira.eduuni.fi/browse/OPHJOD-1779
=> OPHJOD-1779: Update Node.js version to lts/jod

src/i18n/fi/translation.json
- Update translation
https://jira.eduuni.fi/browse/OPHJOD-1825
=> OPHJOD-1825: Update translation

e2e/WorkHistoryWizard.spec.ts, e2e/fixtures.ts, package-lock.json
Add e2e tests for WorkhistoryWizard
https://jira.eduuni.fi/browse/OPHJOD-1820
=> OPHJOD-1820: Add e2e tests for WorkHistoryWizard

src/routes/Profile/WorkHistory/WorkHistoryWizard/WorkplaceStep.tsx
Fix the delay in input validation for Datepicker in WorkplaceStep when using keyboard.
https://jira.eduuni.fi/browse/OPHJOD-1817
=> OPHJOD-1817: Fix validation delay in WorkplaceStep

src/i18n/fi/translation.json, src/routes/Profile/Competences/Competences.tsx, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivities.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/routes/Profile/WorkHistory/WorkHistory.tsx
- Add links to opportunities in profile sections
https://jira.eduuni.fi/browse/OPHJOD-1746
=> OPHJOD-1746: Add links to opportunities in profile sections

src/components/MainLayout/MainLayout.tsx, src/components/OpportunityDetails/OpportunityDetails.tsx, src/routes/BasicInformation/BasicInformation.tsx, src/routes/LandingPage/LandingPage.tsx, src/routes/Profile/EducationHistory/EducationHistory.tsx, src/routes/Profile/FreeTimeActivities/FreeTimeActivities.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/MyGoals/MyGoals.tsx, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Profile/ProfileFront/ProfileFront.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/routes/Profile/WorkHistory/WorkHistory.tsx, src/routes/UserGuide/UserGuide.tsx
- Fix MainLayout navChildren
https://jira.eduuni.fi/browse/OPHJOD-1840
=> OPHJOD-1840: Fix MainLayout navChildren

src/components/NavMenu/menuRoutes.tsx
Navigate to login page when trying to navigate to profile without authentication
https://jira.eduuni.fi/browse/OPHJOD-1867
=> OPHJOD-1867: Navigate to login page when trying to navigate to profile without authentication

src/components/NavMenu/NavLinkBasedOnAuth.test.tsx, src/components/NavMenu/NavLinkBasedOnAuth.tsx, src/routes/LandingPage/LandingPage.tsx
Fix login callback url, `/lang/` needed to be stripped
https://jira.eduuni.fi/browse/OPHJOD-1869
=> OPHJOD-1869: Fix login callback url

e2e/EducationHistoryWizard.spec.ts, e2e/FreeTimeActivitiesWizard.spec.ts, e2e/WorkHistoryWizard.spec.ts, e2e/mocks.ts
Update e2e tests of profile
- Remove "heading" and "title" tests
- Refactored common methods to separate file
https://jira.eduuni.fi/browse/OPHJOD-1875
=> OPHJOD-1875: Update e2e tests of profile

src/components/NavMenu/NavLinkBasedOnAuth.test.tsx, src/components/NavMenu/NavLinkBasedOnAuth.tsx, src/components/NavMenu/menuRoutes.tsx
* Fixed profile links, which broke in this PR due to an oversight: https://github.com/Opetushallitus/jod-yksilo-ui/pull/533
* The language part of the link should have been removed only for the login callback URL, not from normal links
https://jira.eduuni.fi/browse/OPHJOD-1869
=> OPHJOD-1869: Fix profile links not working

src/components/Toaster/Toaster.tsx, src/components/Toaster/toaster.css
Add slide-in animation to toast. Use css styles because of _react-hot-toast/headless_
https://jira.eduuni.fi/browse/OPHJOD-1893
=> OPHJOD-1893: Add slide-in animation to toast

src/components/AiInfo/AiInfo.tsx, src/components/CompareTable/CompareCompetencesTable.tsx, src/components/JakaumaList/JakaumaList.tsx, src/components/OpportunityDetails/OpportunityDetails.tsx, src/components/ScrollHeading/ScrollHeading.tsx, src/components/createLoginDialogFooter.tsx, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/i18n/sv/translation.json, src/routes/EducationOpportunity/EducationOpportunity.tsx, src/routes/JobOpportunity/JobOpportunity.tsx, src/utils/routeUtils.tsx
Update job and education opportunity pages to match latest design
https://jira.eduuni.fi/browse/OPHJOD-1895
Koulutusmahdollisuus desktop:
Työmahdollisuus desktop:
Työmahdollisuus mobile:
=> OPHJOD-1895: Update opportunity pages to match latest design

src/routes/EducationOpportunity/EducationOpportunity.tsx, src/routes/JobOpportunity/JobOpportunity.tsx
Fixed the svg logos not appearing in opportunity pages by importing them, instead of just referring them in src string
https://jira.eduuni.fi/browse/OPHJOD-1891
=> OPHJOD-1891: Fix svg images not loading in opportunity pages

src/components/OpportunityDetails/OpportunityDetails.tsx
Fix icons on the OpportunityDetails.
https://jira.eduuni.fi/browse/OPHJOD-1932
=> OPHJOD-1932: Fix icons on OpportunityDetails

src/components/OpportunityDetails/OpportunityDetails.tsx, src/components/RateAiContent/RateAiContent.tsx, src/i18n/fi/translation.json, src/routes/EducationOpportunity/EducationOpportunity.tsx, src/routes/JobOpportunity/JobOpportunity.tsx
Updated design of feedback element. Currently no backend implementation for giving feedback. 
https://jira.eduuni.fi/browse/OPHJOD-1887
=> OPHJOD-1887: Update upvote/downvote element design

src/routes/Root/Root.tsx, vite.config.ts
- Use root level manifest and favicon
https://jira.eduuni.fi/browse/OPHJOD-1996
=> OPHJOD-1996: Use root level manifest and favicon

src/components/CounselingBanner/CounselingBanner.tsx, src/components/OpportunityDetails/OpportunityDetails.tsx, src/i18n/fi/translation.json, src/routes/JobOpportunity/JobOpportunity.tsx
Add service catalog banner to opportunities.
https://jira.eduuni.fi/browse/OPHJOD-1928
=> OPHJOD-1928: Add service catalog banner to opportunities

src/routes/Tool/Interests.tsx
OPHJOD-1936: Hide virtual assistant in production environment
https://jira.eduuni.fi/browse/OPHJOD-1936
=> OPHJOD-1936: Hide virtual assistant in production environment

src/routes/Tool/Tool.tsx, src/routes/Tool/ToolOpportunityCardActionMenu.tsx
Fix share link not working on opportunity tool
https://jira.eduuni.fi/browse/OPHJOD-1912
=> OPHJOD-1912: Fix share link not working on opportunity tool

src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/i18n/fi/translation.json, src/routes/Tool/CategorizedCompetenceTagList.tsx, src/routes/Tool/Tool.tsx
* **Update translations in tool**
* **Fix typo in translation key when deleting mapped competences**
*  **Filter empty competence categories out in `CategorizedCompetenceTagList` to prevent empty DOM elements**
* **Minor unrelated design changes**
* Tietosi/mahdollisuutesi titles: size from `h3` to `h2`
* Tietosi accordion boxes, smaller gap: `24px` to `12px`
* Update/Päivitä button size to `lg`
* Osaamissuosittelija placeholder font size to `text-body-sm`
https://jira.eduuni.fi/browse/OPHJOD-2017
=> OPHJOD-2017: Update tool translations and styling

src/routes/Profile/MyGoals/MyGoalsSection.tsx
Hide path functionality from production environment
https://jira.eduuni.fi/browse/OPHJOD-2044
=> OPHJOD-2044: Hide path functionality from production environment

src/api/schema.d.ts, src/i18n/fi/translation.json, src/routes/JobOpportunity/JobOpportunity.tsx
Käytä backendinä tätä haaraa https://github.com/Opetushallitus/jod-yksilo/pull/181. Muuten näkyy vain että tiedot ei saatavilla
https://jira.eduuni.fi/browse/OPHJOD-1974
=> Ophjod 1974 job opportunity salary data

e2e/fixtures.ts, src/api/schema.d.ts, src/i18n/fi/translation.json, src/routes/Profile/Preferences/Preferences.tsx
Poistettu lupaArkistoida
https://jira.eduuni.fi/browse/OPHJOD-2056
=> OPHJOD-2056: Remove lupaArkistoida

package-lock.json, src/components/MobileFilterButton/MobileFilterButton.tsx
`RoundButton` moved from DS to yksilo-ui with small refactoring
https://jira.eduuni.fi/browse/OPHJOD-1807
=> OPHJOD-1807: Update MobileFilterButton

src/routes/JobOpportunity/JobOpportunity.tsx
Show ammattiryhmä description instead of työmahdollisuus description under ammattiryhmä section
https://jira.eduuni.fi/browse/OPHJOD-2045
=> OPHJOD-2045: Show the right description for ammattiryhmä

src/routes/Home/Home.tsx
- Update hero image
https://jira.eduuni.fi/browse/OPHJOD-2161
=> OPHJOD-2161: Update hero image

src/components/OpportunityDetails/OpportunityDetails.tsx, src/components/RateAiContent/RateAiContent.tsx, src/i18n/fi/translation.json, src/routes/EducationOpportunity/EducationOpportunity.tsx, src/routes/JobOpportunity/JobOpportunity.tsx, src/routes/Tool/Tool.tsx
- Update translations for `RateAiContent`
- also the used values was mixed up between `mahdollisuus` and `kohtaanto`
- refactored the translation structure to be clearer
- refactored to no longer use default export, as we use named ones.
https://jira.eduuni.fi/browse/OPHJOD-2105
=> OPHJOD-2105: Update RateAiContent translations

src/routes/Profile/WelcomePathModal/WelcomePathModal.tsx
Fix email is not saved
https://jira.eduuni.fi/browse/OPHJOD-1842
=> OPHJOD-1842: Fix email is not saved

package-lock.json, src/i18n/fi/translation.json, src/routes/Root/Root.tsx
- Update footer information
https://jira.eduuni.fi/browse/OPHJOD-2235
=> OPHJOD-2235: Update footer information

package-lock.json, src/components/NavMenu/NavMenu.tsx, src/components/NavMenu/menuRoutes.tsx, src/hooks/useAppRoutes/index.ts, src/i18n/fi/translation.json
* Update DS (to get the updated `NavigationMenu`)
* Updated translations and navigation menu ordering
https://jira.eduuni.fi/browse/OPHJOD-2241
=> OPHJOD-2241: Update navigation menu translations, ordering and DS

src/routes/Root/Root.tsx
- Update feedback background image
https://jira.eduuni.fi/browse/OPHJOD-2145
=> OPHJOD-2145: Update feedback background image

src/components/OpportunityCard/OpportunityCard.tsx
https://jira.eduuni.fi/browse/OPHJOD-
=> OPHJOD-2325: Show ammattiryhma in all environments

src/routes/Home/Home.tsx
Fix frontpage link 
https://jira.eduuni.fi/browse/OPHJOD-2329
=> OPHJOD-2329: Change beta link address

src/components/OpportunityDetails/OpportunityDetails.tsx, src/components/RateAiContent/RateAiContent.tsx, src/i18n/fi/translation.json, src/routes/EducationOpportunity/EducationOpportunity.tsx, src/routes/JobOpportunity/JobOpportunity.tsx, src/routes/Tool/Tool.tsx
- Implement rate AI submission
https://jira.eduuni.fi/browse/OPHJOD-2319
=> OPHJOD-2319: Implement rate AI submission

src/routes/Home/Home.tsx
- Update background image
https://jira.eduuni.fi/browse/OPHJOD-2141
=> OPHJOD-2141: Update background image

src/components/RateAiContent/RateAiContent.tsx
- Remove unwanted environment hook
https://jira.eduuni.fi/browse/OPHJOD-2368
=> OPHJOD-2368: Remove unwanted environment hook

src/routes/Root/Root.tsx
Change beta survey url
https://jira.eduuni.fi/browse/OPHJOD-2376
=> OPHJOD-2376: Change webropol url

src/components/OpportunityCard/OpportunityCard.tsx, src/i18n/fi/translation.json
- Add tooltip for job opportunity group information
https://jira.eduuni.fi/browse/OPHJOD-2358
=> OPHJOD-2358: Add tooltip for job opportunity group information

src/components/NavMenu/NavMenu.tsx, src/i18n/fi/translation.json
-  Update PortalLink to use localized URL
- Fix some typos
https://jira.eduuni.fi/browse/OPHJOD-1920
=> OPHJOD-1920 & OPHJOD-1916 & OPHJOD-1918

src/routes/Tool/Tool.tsx, src/routes/Tool/ToolSettings.tsx
Show update button in tool on mobile
https://jira.eduuni.fi/browse/OPHJOD-2361
=> OPHJOD-2361: Show update button in tool on mobile

package-lock.json, src/components/ExperienceTable/ExperienceTableRow.tsx, src/components/OsaamisSuosittelija/AddedTags.tsx, src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/routes/Profile/Competences/GroupByAlphabet.tsx, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/Path/VaiheCard.tsx, src/routes/Profile/Path/modal/ProposeVaiheModal/VaiheOpportunityCard.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx
- Replace title attributes with tooltip
https://jira.eduuni.fi/browse/OPHJOD-2121
=> OPHJOD-2121: Replace title attributes with tooltip

src/i18n/fi/translation.json, src/routes/index.tsx
- Fix typos and improve translations
https://jira.eduuni.fi/browse/OPHJOD-2393
=> OPHJOD-2393: Fix typos and improve translations

src/components/ExperienceTable/ExperienceTableRow.tsx, src/components/OsaamisSuosittelija/OsaamisSuosittelija.tsx, src/routes/Profile/Competences/GroupByAlphabet.tsx, src/routes/Profile/Competences/GroupBySource.tsx, src/routes/Profile/Interests/Interests.tsx, src/routes/Profile/Path/VaiheCard.tsx, src/routes/Profile/Path/modal/ProposeVaiheModal/VaiheOpportunityCard.tsx, src/routes/Profile/SomethingElse/SomethingElse.tsx, src/routes/Tool/VirtualAssistant.tsx
- Improve tags accebility
https://jira.eduuni.fi/browse/OPHJOD-2030
=> OPHJOD-2030: Improve tags accebility
